Repository azjezz/psl, pull requests merged in 2020-11, with the labels that each got.

#98 [Iter] Improve reduce signature
  src/Psl/Iter/reduce.php
Labels: Status: Review Needed

#74 [Str] add grarpheme support
  composer.json
  src/Psl/Internal/Loader.php
  src/Psl/Str/Grapheme/contains.php
  src/Psl/Str/Grapheme/contains_ci.php
  src/Psl/Str/Grapheme/ends_with.php
  src/Psl/Str/Grapheme/ends_with_ci.php
  src/Psl/Str/Grapheme/length.php
  src/Psl/Str/Grapheme/search.php
  src/Psl/Str/Grapheme/search_ci.php
  src/Psl/Str/Grapheme/search_last.php
  src/Psl/Str/Grapheme/search_last_ci.php
  src/Psl/Str/Grapheme/slice.php
  src/Psl/Str/Grapheme/starts_with.php
  src/Psl/Str/Grapheme/starts_with_ci.php
  src/Psl/Str/Grapheme/strip_prefix.php
  src/Psl/Str/Grapheme/strip_suffix.php
  tests/Psl/Str/Grapheme/ContainsCiTest.php
  tests/Psl/Str/Grapheme/ContainsTest.php
  tests/Psl/Str/Grapheme/EndsWithCiTest.php
  tests/Psl/Str/Grapheme/EndsWithTest.php
  tests/Psl/Str/Grapheme/LengthTest.php
  tests/Psl/Str/Grapheme/SearchCiTest.php
  tests/Psl/Str/Grapheme/SearchLastCiTest.php
  tests/Psl/Str/Grapheme/SearchLastTest.php
  tests/Psl/Str/Grapheme/SearchTest.php
  tests/Psl/Str/Grapheme/SliceTest.php
  tests/Psl/Str/Grapheme/StartsWithCiTest.php
  tests/Psl/Str/Grapheme/StartsWithTest.php
  tests/Psl/Str/Grapheme/StripPrefixTest.php
  tests/Psl/Str/Grapheme/StripSuffixTest.php
Labels: Status: Review Needed, Type: Enhancement, hacktoberfest-accepted

#101 [Type] replace `Type\arr` by `Type\{mutable_}map` and `Type\{mutable_}vector`
  src/Psl/Internal/Loader.php
  src/Psl/Type/Internal/MapType.php
  src/Psl/Type/Internal/MutableMapType.php
  src/Psl/Type/Internal/MutableVectorType.php
  src/Psl/Type/Internal/VectorType.php
  src/Psl/Type/map.php
  src/Psl/Type/mutable_map.php
  src/Psl/Type/mutable_vector.php
  src/Psl/Type/vector.php
  tests/Psl/Json/TypedTest.php
  tests/Psl/Type/ArrayTypeTest.php
  tests/Psl/Type/MapTypeTest.php
  tests/Psl/Type/MutableMapTypeTest.php
  tests/Psl/Type/MutableVectorTypeTest.php
  tests/Psl/Type/TypeTest.php
  tests/Psl/Type/VectorTypeTest.php
Labels: Status: Review Needed, Type: Enhancement
