Repository azjezz/psl, pull requests merged in 2020-09, with the labels that each got.

#48 [Env] initial commit
  src/Psl/Env/args.php
  src/Psl/Env/current_dir.php
  src/Psl/Env/current_exec.php
  src/Psl/Env/get_var.php
  src/Psl/Env/get_vars.php
  src/Psl/Env/join_paths.php
  src/Psl/Env/remove_var.php
  src/Psl/Env/set_current_dir.php
  src/Psl/Env/set_var.php
  src/Psl/Env/split_paths.php
  src/Psl/Env/temp_dir.php
  src/Psl/Internal/Loader.php
  tests/Psl/Env/ArgsTest.php
  tests/Psl/Env/CurrentDirTest.php
  tests/Psl/Env/CurrentExecTest.php
  tests/Psl/Env/GetVarTest.php
  tests/Psl/Env/GetVarsTest.php
  tests/Psl/Env/JoinPathsTest.php
  tests/Psl/Env/RemoveVarTest.php
  tests/Psl/Env/SplitPathsTest.php
  tests/Psl/Env/TempDirTest.php
Labels: Priority: High, Status: Revision Needed, Type: Enhancement

#49 add CODE OF CONDUCT
  CODE_OF_CONDUCT.md
Labels: Status: Accepted

#51 [Password] initial commit
  .travis.yml
  README.md
  appveyor.yml
  composer.json
  src/Psl/Internal/Loader.php
  src/Psl/Password/algorithms.php
  src/Psl/Password/constants.php
  src/Psl/Password/get_information.php
  src/Psl/Password/hash.php
  src/Psl/Password/needs_rehash.php
  src/Psl/Password/verify.php
  tests/Psl/Password/PasswordTest.php
Labels: Status: In Progress, Type: Enhancement

#54 [Observer] introduce the observer design-pattern
  src/Psl/Internal/Loader.php
  src/Psl/Observer/ObserverInterface.php
  src/Psl/Observer/SubjectInterface.php
Labels: Priority: Low, Status: Completed, Type: Enhancement

#55 [Str] Add the ability to supply string encoding
  src/Psl/Internal/Loader.php
  src/Psl/Internal/internal_encoding.php
  src/Psl/Str/capitalize.php
  src/Psl/Str/capitalize_words.php
  src/Psl/Str/chr.php
  src/Psl/Str/chunk.php
  src/Psl/Str/contains.php
  src/Psl/Str/contains_ci.php
  src/Psl/Str/encoding.php
  src/Psl/Str/ends_with.php
  src/Psl/Str/ends_with_ci.php
  src/Psl/Str/fold.php
  src/Psl/Str/format.php
  src/Psl/Str/format_number.php
  src/Psl/Str/join.php
  src/Psl/Str/length.php
  src/Psl/Str/lowercase.php
  src/Psl/Str/ord.php
  src/Psl/Str/pad_left.php
  src/Psl/Str/pad_right.php
  src/Psl/Str/repeat.php
  src/Psl/Str/replace.php
  src/Psl/Str/replace_ci.php
  src/Psl/Str/replace_every.php
  src/Psl/Str/replace_every_ci.php
  src/Psl/Str/search.php
  src/Psl/Str/search_ci.php
  src/Psl/Str/search_last.php
  src/Psl/Str/search_last_ci.php
  src/Psl/Str/slice.php
  src/Psl/Str/splice.php
  src/Psl/Str/split.php
  src/Psl/Str/starts_with.php
  src/Psl/Str/starts_with_ci.php
  src/Psl/Str/strip_prefix.php
  src/Psl/Str/strip_suffix.php
  src/Psl/Str/truncate.php
  src/Psl/Str/uppercase.php
  src/Psl/Str/width.php
  src/Psl/Str/wrap.php
  tests/Psl/Str/EncodingTest.php
Labels: Priority: High, Status: In Progress, Type: Enhancement

#57 [Fun] Add pipe and after combinators
  src/Psl/Fun/after.php
  src/Psl/Fun/pipe.php
  src/Psl/Internal/Loader.php
  tests/Psl/Fun/AfterTest.php
  tests/Psl/Fun/PipeTest.php
Labels: Priority: Medium, Status: Accepted, Type: Enhancement

#61 [Result] Rename Asio namespace
  src/Psl/Asio/wrap.php
  src/Psl/Internal/Loader.php
  src/Psl/Result/Failure.php
  src/Psl/Result/ResultInterface.php
  src/Psl/Result/Success.php
  src/Psl/Result/wrap.php
  tests/Psl/Result/FailureTest.php
  tests/Psl/Result/SuccessTest.php
  tests/Psl/Result/WrapTest.php
Labels: Status: Accepted, Type: Enhancement
