Repository azjezz/psl, pull requests merged in 2020-07, with the labels that each got.

#22 add more tests
  README.md
  psalm.xml
  tests/Psl/Arr/CountValuesTest.php
  tests/Psl/InvariantTest.php
  tests/Psl/Iter/AllTest.php
  tests/Psl/Iter/AnyTest.php
  tests/Psl/Iter/ApplyTest.php
  tests/Psl/Iter/IteratorTest.php
  tests/Psl/SequenceTest.php
Labels: enhancement

#24 improve type coverage
  .scrutinizer.yml
  src/Psl/Arr/first.php
  src/Psl/Arr/random.php
  src/Psl/Gen/product.php
  src/Psl/Gen/range.php
  src/Psl/Iter/count.php
  src/Psl/Str/levenshtein.php
  src/Psl/Str/trim.php
  src/Psl/Str/trim_left.php
  src/Psl/Str/trim_right.php
Labels: enhancement

#31 add roave security advisories, and psalm taint analysis
  .travis.yml
  composer.json
Labels: Status: Accepted, Type: Enhancement, Type: Maintenance

#32 remove function stubs from psalm configurations
  psalm.xml
  src/Psl/Arr/sort_by.php
  src/Psl/Arr/sort_with_keys.php
  src/Psl/Arr/sort_with_keys_by.php
  src/Psl/Gen/product.php
Labels: Status: Accepted, Type: Maintenance

#33 [Tests] use self:: instead of $this-> to access assertation methods
  tests/Psl/Asio/WrapTest.php
  tests/Psl/Asio/WrappedExceptionTest.php
  tests/Psl/Asio/WrappedResultTest.php
  tests/Psl/Collection/AbstractMapTest.php
  tests/Psl/Collection/AbstractVectorTest.php
  tests/Psl/Collection/MutableMapTest.php
  tests/Psl/Collection/MutableVectorTest.php
  tests/Psl/Gen/RewindableGeneratorTest.php
  tests/Psl/Iter/AllTest.php
  tests/Psl/Iter/AnyTest.php
  tests/Psl/Iter/ApplyTest.php
  tests/Psl/Iter/IteratorTest.php
  tests/Psl/SequenceTest.php
Labels: Status: Accepted, Type: Maintenance

#35 run tests on appveyor
  appveyor.yml
Labels: Status: Available

#34 [Iter] add tests
  phpunit.xml.dist
  src/Psl/Gen/diff_by_key.php
  src/Psl/Iter/diff_by_key.php
  tests/Psl/Iter/ChainTest.php
  tests/Psl/Iter/ChunkTest.php
  tests/Psl/Iter/ChunkWithKeysTest.php
  tests/Psl/Iter/ContainsKeyTest.php
  tests/Psl/Iter/ContainsTest.php
  tests/Psl/Iter/CountTest.php
  tests/Psl/Iter/DiffByKeyTest.php
  tests/Psl/Iter/DropTest.php
  tests/Psl/Iter/DropWhileTest.php
  tests/Psl/Iter/EnumerateTest.php
  tests/Psl/Iter/FilterKeysTest.php
  tests/Psl/Iter/FilterNullsTest.php
  tests/Psl/Iter/IteratorTest.php
Labels: Status: Accepted, Type: Enhancement

#38 remove type check command
  composer.json
Labels: Priority: Critical, Status: Accepted, Type: Maintenance

#37 add pseudo random functions
  src/Psl/Arr/random.php
  src/Psl/Internal/Loader.php
  src/Psl/PseudoRandom/float.php
  src/Psl/PseudoRandom/int.php
  src/Psl/SecureRandom/bytes.php
  src/Psl/SecureRandom/float.php
  src/Psl/SecureRandom/int.php
  src/Psl/SecureRandom/string.php
  tests/Psl/PseudoRandom/FloatTest.php
  tests/Psl/PseudoRandom/IntTest.php
  tests/Psl/SecureRandom/BytesTest.php
  tests/Psl/SecureRandom/FloatTest.php
  tests/Psl/SecureRandom/IntTest.php
  tests/Psl/SecureRandom/StringTest.php
Labels: Status: Available, Status: Review Needed, Type: Enhancement

#39 use shout-case for constants
  src/Psl/Internal/Loader.php
Labels: Priority: High, Status: Accepted, Type: Enhancement
