Repository azjezz/psl, pull requests merged in 2020-10, with the labels that each got.

#70 Migrate to GitHub actions
  .coveralls.yml
  .github/workflows/coding-standards.yml
  .github/workflows/security-analysis.yml
  .github/workflows/static-analysis.yml
  .github/workflows/unit-tests.yml
  .travis.yml
  README.md
  composer.json
Labels: Hacktoberfest, Status: Accepted, Type: Enhancement

#65 [Result] Add proceed and then with helper functions
  src/Psl/Fun/passthrough.php
  src/Psl/Fun/rethrow.php
  src/Psl/Internal/Loader.php
  src/Psl/Result/Failure.php
  src/Psl/Result/ResultInterface.php
  src/Psl/Result/Success.php
  tests/Psl/Fun/PassthroughTest.php
  tests/Psl/Fun/RethrowTest.php
  tests/Psl/Result/FailureTest.php
  tests/Psl/Result/SuccessTest.php
Labels: Hacktoberfest, Status: Revision Needed, Type: Enhancement

#72 [Str] add encoding function
  src/Psl/Internal/Loader.php
  src/Psl/Internal/internal_encoding.php
  src/Psl/Internal/is_encoding_valid.php
  src/Psl/Str/convert_encoding.php
  src/Psl/Str/detect_encoding.php
  src/Psl/Str/encoding.php
  src/Psl/Str/is_utf8.php
  tests/Psl/Str/ConvertEncodingTest.php
  tests/Psl/Str/DetectEncodingTest.php
  tests/Psl/Str/IsUTF8Test.php
Labels: Status: In Progress, Status: Revision Needed, Type: Enhancement, hacktoberfest

#79 use TravisCI to send code coverage
  .coveralls.yml
  .github/workflows/unit-tests.yml
  .travis.yml
  README.md
  composer.json
Labels: Status: In Progress, Type: Enhancement

#76 fix consistency in parameter names + some cleanup
  src/Psl/Arr/contains.php
  src/Psl/Fun/after.php
  src/Psl/Fun/passthrough.php
  src/Psl/Fun/pipe.php
  src/Psl/Fun/rethrow.php
  src/Psl/Math/div.php
  src/Psl/Str/Byte/capitalize.php
  src/Psl/Str/Byte/capitalize_words.php
  src/Psl/Str/Byte/chr.php
  src/Psl/Str/Byte/chunk.php
  src/Psl/Str/Byte/compare.php
  src/Psl/Str/Byte/compare_ci.php
  src/Psl/Str/Byte/ends_with_ci.php
  src/Psl/Str/Byte/length.php
  src/Psl/Str/Byte/lowercase.php
  src/Psl/Str/Byte/ord.php
  src/Psl/Str/Byte/pad_left.php
  src/Psl/Str/Byte/pad_right.php
  src/Psl/Str/Byte/replace.php
  src/Psl/Str/Byte/replace_ci.php
  src/Psl/Str/Byte/replace_every.php
  src/Psl/Str/Byte/replace_every_ci.php
  src/Psl/Str/Byte/rot13.php
  src/Psl/Str/Byte/search.php
  src/Psl/Str/Byte/search_ci.php
  src/Psl/Str/Byte/search_last.php
  src/Psl/Str/Byte/shuffle.php
  src/Psl/Str/Byte/slice.php
  src/Psl/Str/Byte/splice.php
  src/Psl/Str/Byte/split.php
  src/Psl/Str/Byte/starts_with.php
  src/Psl/Str/Byte/starts_with_ci.php
  src/Psl/Str/Byte/trim.php
  src/Psl/Str/Byte/trim_left.php
  src/Psl/Str/Byte/trim_right.php
  src/Psl/Str/Byte/uppercase.php
  src/Psl/Str/Byte/wrap.php
  src/Psl/Str/chr.php
  src/Psl/Str/chunk.php
  src/Psl/Str/fold.php
  src/Psl/Str/from_code_points.php
  src/Psl/Str/length.php
  src/Psl/Str/levenshtein.php
  src/Psl/Str/lowercase.php
  src/Psl/Str/metaphone.php
  src/Psl/Str/ord.php
  src/Psl/Str/replace.php
  src/Psl/Str/starts_with.php
  src/Psl/Str/starts_with_ci.php
  src/Psl/Str/truncate.php
  src/Psl/Str/width.php
  src/Psl/Type/arr.php
  src/Psl/Type/intersection.php
  src/Psl/Type/union.php
  src/Psl/invariant_violation.php
Labels: Priority: Medium, Status: Completed, Type: Bug

#53 [DataStructure] Introduce the DataStructure component
  src/Psl/Arr/idx.php
  src/Psl/DataStructure/PriorityQueue.php
  src/Psl/DataStructure/PriorityQueueInterface.php
  src/Psl/DataStructure/Queue.php
  src/Psl/DataStructure/QueueInterface.php
  src/Psl/DataStructure/Stack.php
  src/Psl/DataStructure/StackInterface.php
  src/Psl/Iter/Iterator.php
  tests/Psl/DataStructure/PriorityQueueTest.php
  tests/Psl/DataStructure/QueueTest.php
  tests/Psl/DataStructure/StackTest.php
Labels: Priority: Medium, Status: Review Needed, Type: Enhancement

#85 [Fun] Add when function
  src/Psl/Fun/when.php
  src/Psl/Internal/Loader.php
  tests/Psl/Fun/WhenTest.php
Labels: Status: Completed, Type: Enhancement

#86 [Iter] Improve Iterable factories
  src/Psl/Fun/identity.php
  src/Psl/Fun/when.php
  src/Psl/Internal/Loader.php
  src/Psl/Internal/lazy_iterator.php
  src/Psl/Iter/Iterator.php
  src/Psl/Iter/chain.php
  src/Psl/Iter/chunk.php
  src/Psl/Iter/chunk_with_keys.php
  src/Psl/Iter/diff_by_key.php
  src/Psl/Iter/drop_while.php
  src/Psl/Iter/enumerate.php
  src/Psl/Iter/filter.php
  src/Psl/Iter/filter_keys.php
  src/Psl/Iter/filter_nulls.php
  src/Psl/Iter/filter_with_key.php
  src/Psl/Iter/flatten.php
  src/Psl/Iter/flip.php
  src/Psl/Iter/from_entries.php
  src/Psl/Iter/from_keys.php
  src/Psl/Iter/keys.php
  src/Psl/Iter/map.php
  src/Psl/Iter/map_keys.php
  src/Psl/Iter/map_with_key.php
  src/Psl/Iter/product.php
  src/Psl/Iter/pull.php
  src/Psl/Iter/pull_with_key.php
  src/Psl/Iter/range.php
  src/Psl/Iter/reductions.php
  src/Psl/Iter/reindex.php
  src/Psl/Iter/repeat.php
  src/Psl/Iter/reproduce.php
  src/Psl/Iter/reverse.php
  src/Psl/Iter/slice.php
  src/Psl/Iter/take_while.php
  src/Psl/Iter/values.php
  src/Psl/Iter/zip.php
  tests/Psl/Fun/IdentityTest.php
  tests/Psl/Fun/PassthroughTest.php
  tests/Psl/Fun/RethrowTest.php
  tests/Psl/Iter/IteratorTest.php
  tests/Psl/Iter/ReproduceTest.php
  tests/Psl/Result/SuccessTest.php
Labels: Status: Revision Needed, Type: Enhancement

#90 [Hash] introduce the Hash API
  src/Psl/Hash/Context.php
  src/Psl/Hash/Hmac/algorithms.php
  src/Psl/Hash/Hmac/hash.php
  src/Psl/Hash/algorithms.php
  src/Psl/Hash/equals.php
  src/Psl/Hash/hash.php
  src/Psl/Internal/Loader.php
  tests/Psl/Hash/AlgorithmsTest.php
  tests/Psl/Hash/ContextTest.php
  tests/Psl/Hash/EqualsTest.php
  tests/Psl/Hash/HashTest.php
  tests/Psl/Hash/Hmac/AlgorithmsTest.php
  tests/Psl/Hash/Hmac/HashTest.php
Labels: Status: Review Needed, Type: Enhancement

#92 support php 8
  composer.json
Labels: Status: Accepted, Type: Enhancement

#88 [XML] Basic error handling
  .github/workflows/coding-standards.yml
  .github/workflows/security-analysis.yml
  .github/workflows/static-analysis.yml
  .github/workflows/unit-tests.yml
  composer.json
  src/Psl/Internal/Loader.php
  src/Psl/Xml/Exception/ExceptionInterface.php
  src/Psl/Xml/Exception/RuntimeException.php
  src/Psl/Xml/Internal/detect_errors.php
  src/Psl/Xml/Internal/issue_collection_from_xml_errors.php
  src/Psl/Xml/Internal/issue_from_xml_error.php
  src/Psl/Xml/Internal/issue_level_from_xml_error.php
  src/Psl/Xml/Issue/Issue.php
  src/Psl/Xml/Issue/IssueCollection.php
  src/Psl/Xml/Issue/Level.php
  tests/Psl/Xml/Exception/XmlExceptionTest.php
  tests/Psl/Xml/Internal/DetectErrorsTest.php
  tests/Psl/Xml/Internal/IssueCollectionFromXmlErrorsTest.php
  tests/Psl/Xml/Internal/IssueFromXmlErrorTest.php
  tests/Psl/Xml/Internal/IssueLevelFromXmlErrorTest.php
  tests/Psl/Xml/Issue/IssueCollectionTest.php
  tests/Psl/Xml/Issue/IssueTest.php
  tests/Psl/Xml/Issue/LevelTest.php
  tests/Psl/Xml/Issue/UseIssueTrait.php
Labels: Status: Review Needed, Type: Enhancement
