Repository azjezz/psl, pull requests merged in 2021-01, with the labels that each got.

#108 ci: run code coverage in GA
  .coveralls.yml
  .github/workflows/code-coverage.yml
  .stickler.yml
  .travis.yml
  composer.json
Labels: Priority: High, Status: Available, Type: Maintenance

#109 update git attributes
  .gitattributes
Labels: Priority: Low, Status: Completed, Type: Enhancement, Type: Maintenance

#111 [Math] clamp function
  src/Psl/Internal/Loader.php
  src/Psl/Math/clamp.php
  tests/Psl/Math/ClampTest.php
Labels: Status: Accepted, Type: Enhancement

#114 [Result] don't wrap results on success.
  src/Psl/Result/wrap.php
  tests/Psl/Result/WrapTest.php
Labels: Priority: Medium, Status: Accepted, Type: Bug
