Repository azjezz/psl, pull requests merged in 2021-11, with the labels that each got.

#246 chore: drop support for PHP 8.0
  .github/workflows/benchmarks.yml
  .github/workflows/code-coverage.yml
  .github/workflows/coding-standards.yml
  .github/workflows/documentation-check.yml
  .github/workflows/security-analysis.yml
  .github/workflows/static-analysis.yml
  .github/workflows/unit-tests.yml
  Makefile
  composer.json
  composer.lock
  src/Psl/Internal/internal_encoding.php
  src/Psl/Iter/Iterator.php
  tests/unit/Str/WidthTest.php
Labels: Priority: Medium, Status: Completed, Type: Enhancement

#247 chore: update configuration files
  config/.phpcs.xml
  config/psalm.xml
Labels: Priority: Medium, Status: Completed, Type: Enhancement

#244 feat(async): add async I/O support
  .github/workflows/unit-tests.yml
  CHANGELOG.md
  docs/README.md
  docs/component/async.md
  docs/documenter.php
  src/Psl/Async/Awaitable.php
  src/Psl/Async/Deferred.php
  src/Psl/Async/Exception/CompositeException.php
  src/Psl/Async/Exception/ExceptionInterface.php
  src/Psl/Async/Exception/RuntimeException.php
  src/Psl/Async/Exception/TimeoutException.php
  src/Psl/Async/Exception/UnhandledAwaitableException.php
  src/Psl/Async/Internal/AwaitableIterator.php
  src/Psl/Async/Internal/AwaitableIteratorQueue.php
  src/Psl/Async/Internal/State.php
  src/Psl/Async/Scheduler.php
  src/Psl/Async/all.php
  src/Psl/Async/any.php
  src/Psl/Async/await.php
  src/Psl/Async/await_readable.php
  src/Psl/Async/await_signal.php
  src/Psl/Async/await_writable.php
  src/Psl/Async/concurrently.php
  src/Psl/Async/first.php
  src/Psl/Async/later.php
  src/Psl/Async/run.php
  src/Psl/Async/usleep.php
  src/Psl/Internal/Loader.php
  tests/unit/Async/AnyTest.php
  tests/unit/Async/AwaitReadableTest.php
  tests/unit/Async/AwaitableTest.php
  tests/unit/Async/DeferredTest.php
  tests/unit/Async/Exception/CompositeExceptionTest.php
  tests/unit/Async/FirstTest.php
  tests/unit/Async/RunTest.php
Labels: Priority: High, Status: In Progress, Type: Enhancement

#249 feat(io): refactor IO component to use Async component
  docs/component/io.md
  src/Psl/Async/await_readable.php
  src/Psl/Async/await_signal.php
  src/Psl/Async/await_writable.php
  src/Psl/Async/concurrently.php
  src/Psl/Async/run.php
  src/Psl/IO/Exception/TimeoutException.php
  src/Psl/IO/Internal/OptionalIncrementalTimeout.php
  src/Psl/IO/Internal/ReadOnlyHandleDecorator.php
  src/Psl/IO/Internal/ResourceHandle.php
  src/Psl/IO/Internal/WriteOnlyHandleDecorator.php
  src/Psl/IO/Internal/open.php
  src/Psl/IO/Internal/open_resource.php
  src/Psl/IO/MemoryHandle.php
  src/Psl/IO/ReadHandleConvenienceMethodsTrait.php
  src/Psl/IO/ReadHandleInterface.php
  src/Psl/IO/Reader.php
  src/Psl/IO/Stream/StreamCloseHandle.php
  src/Psl/IO/Stream/StreamCloseReadHandle.php
  src/Psl/IO/Stream/StreamCloseReadWriteHandle.php
  src/Psl/IO/Stream/StreamCloseSeekHandle.php
  src/Psl/IO/Stream/StreamCloseSeekReadHandle.php
  src/Psl/IO/Stream/StreamCloseSeekReadWriteHandle.php
  src/Psl/IO/Stream/StreamCloseSeekWriteHandle.php
  src/Psl/IO/Stream/StreamCloseWriteHandle.php
  src/Psl/IO/Stream/StreamReadHandle.php
  src/Psl/IO/Stream/StreamReadWriteHandle.php
  src/Psl/IO/Stream/StreamSeekHandle.php
  src/Psl/IO/Stream/StreamSeekReadHandle.php
  src/Psl/IO/Stream/StreamSeekReadWriteHandle.php
  src/Psl/IO/Stream/StreamSeekWriteHandle.php
  src/Psl/IO/Stream/StreamWriteHandle.php
  src/Psl/IO/Stream/pipe.php
  src/Psl/IO/WriteHandleConvenienceMethodsTrait.php
  src/Psl/IO/WriteHandleInterface.php
  src/Psl/IO/Writer.php
  src/Psl/IO/error_handle.php
  src/Psl/IO/input_handle.php
  src/Psl/IO/output_handle.php
  src/Psl/Internal/Loader.php
  tests/unit/IO/MemoryHandleTest.php
  tests/unit/IO/Stream/PipeTest.php
Labels: Priority: High, Status: Completed, Type: Enhancement

#250 feat(file): introduce File component
  CHANGELOG.md
  config/.phpcs.xml
  config/psalm.xml
  docs/README.md
  docs/component/file.md
  docs/component/io-stream.md
  docs/documenter.php
  src/Psl/File/Exception/AlreadyLockedException.php
  src/Psl/File/Exception/ExceptionInterface.php
  src/Psl/File/Exception/RuntimeException.php
  src/Psl/File/HandleInterface.php
  src/Psl/File/Internal/AbstractHandleWrapper.php
  src/Psl/File/Internal/ResourceHandle.php
  src/Psl/File/Internal/open.php
  src/Psl/File/Lock.php
  src/Psl/File/LockType.php
  src/Psl/File/ReadHandle.php
  src/Psl/File/ReadHandleInterface.php
  src/Psl/File/ReadWriteHandle.php
  src/Psl/File/ReadWriteHandleInterface.php
  src/Psl/File/WriteHandle.php
  src/Psl/File/WriteHandleInterface.php
  src/Psl/File/WriteMode.php
  src/Psl/File/open_read_only.php
  src/Psl/File/open_read_write.php
  src/Psl/File/open_write_only.php
  src/Psl/File/temporary.php
  src/Psl/IO/Internal/ResourceHandle.php
  src/Psl/Internal/Loader.php
  tests/unit/Async/RunTest.php
  tests/unit/File/LockTest.php
  tests/unit/File/ReadHandleTest.php
  tests/unit/File/ReadWriteHandleTest.php
  tests/unit/File/WriteHandleTest.php
Labels: Priority: High, Status: Completed, Type: Enhancement

#251 feat(filesystem): refactor `Psl\Filesystem\write_file`, `Psl\Filesystem\append_file`, and `Psl\Filesystem\read_file` to use `Psl\File` component.
  .github/workflows/documentation-check.yml
  CHANGELOG.md
  docs/component/filesystem.md
  docs/documenter.php
  src/Psl/File/ReadHandle.php
  src/Psl/File/ReadWriteHandle.php
  src/Psl/File/WriteHandle.php
  src/Psl/Filesystem/Internal/write_file.php
  src/Psl/Filesystem/append_file.php
  src/Psl/Filesystem/read_file.php
  src/Psl/Filesystem/write_file.php
  src/Psl/IO/Internal/ResourceHandle.php
  src/Psl/IO/SeekHandleInterface.php
  src/Psl/Internal/Loader.php
  tests/unit/File/ReadWriteHandleTest.php
  tests/unit/File/WriteHandleTest.php
  tests/unit/Filesystem/FileTest.php
Labels: Priority: High, Status: Completed, Type: Enhancement

#252 feat(shell): refactor `Shell\execute` to use async streams
  CHANGELOG.md
  docs/component/shell.md
  src/Psl/Internal/Loader.php
  src/Psl/Shell/Exception/TimeoutException.php
  src/Psl/Shell/execute.php
Labels: Priority: High, Status: Completed, Type: Enhancement

#253 fix(async): always cancel timeout watcher after suspension is finished.
  docs/component/async.md
  src/Psl/Async/all.php
  src/Psl/Async/await_readable.php
  src/Psl/Async/await_signal.php
  src/Psl/Async/await_writable.php
  src/Psl/Async/run.php
  tests/unit/Async/AllTest.php
Labels: Priority: Critical, Status: Completed, Type: Bug

#255 chore(php): fix PHP 8.1 deprecations
  .github/workflows/unit-tests.yml
  Makefile
  composer.json
  src/Psl/Internal/internal_encoding.php
  src/Psl/Iter/Iterator.php
  tests/unit/Str/WidthTest.php
  tools/php-cs-fixer/composer.lock
Labels: Priority: High, Status: Completed, Type: Enhancement

#256 feat(async): throw if resource is closed while waiting
  docs/component/async.md
  src/Psl/Async/Exception/ResourceClosedException.php
  src/Psl/Async/await_readable.php
  src/Psl/Async/await_writable.php
  src/Psl/Async/main.php
  src/Psl/IO/Internal/ResourceHandle.php
Labels: Priority: High, Status: Completed, Type: Enhancement

#258 feat(runtime): introduce runtime component
  src/Psl/Internal/Loader.php
  src/Psl/Runtime/get_extensions.php
  src/Psl/Runtime/get_sapi.php
  src/Psl/Runtime/get_version.php
  src/Psl/Runtime/get_version_details.php
  src/Psl/Runtime/get_version_id.php
  src/Psl/Runtime/get_zend_extensions.php
  src/Psl/Runtime/get_zend_version.php
  src/Psl/Runtime/has_extension.php
  src/Psl/Runtime/is_debug.php
  src/Psl/Runtime/is_thread_safe.php
  tests/unit/Runtime/DebugTest.php
  tests/unit/Runtime/ExtensionsTest.php
  tests/unit/Runtime/SapiTest.php
  tests/unit/Runtime/ThreadSafetyTest.php
  tests/unit/Runtime/VersionTest.php
  tests/unit/Runtime/ZendTest.php
Labels: Priority: High, Status: Completed, Type: Enhancement

#259 feat(str): use enum for encoding
  config/.phpcs.xml
  docs/component/encoding-base64.md
  docs/component/str.md
  src/Psl/Encoding/Hex/decode.php
  src/Psl/Internal/Loader.php
  src/Psl/Internal/validate_offset.php
  src/Psl/Str/Encoding.php
  src/Psl/Str/after.php
  src/Psl/Str/after_ci.php
  src/Psl/Str/after_last.php
  src/Psl/Str/after_last_ci.php
  src/Psl/Str/before.php
  src/Psl/Str/before_ci.php
  src/Psl/Str/before_last.php
  src/Psl/Str/before_last_ci.php
  src/Psl/Str/capitalize.php
  src/Psl/Str/capitalize_words.php
  src/Psl/Str/chr.php
  src/Psl/Str/chunk.php
  src/Psl/Str/contains.php
  src/Psl/Str/contains_ci.php
  src/Psl/Str/ends_with.php
  src/Psl/Str/ends_with_ci.php
  src/Psl/Str/fold.php
  src/Psl/Str/length.php
  src/Psl/Str/lowercase.php
  src/Psl/Str/ord.php
  src/Psl/Str/pad_left.php
  src/Psl/Str/pad_right.php
  src/Psl/Str/replace.php
  src/Psl/Str/replace_ci.php
  src/Psl/Str/replace_every.php
  src/Psl/Str/replace_every_ci.php
  src/Psl/Str/reverse.php
  src/Psl/Str/search.php
  src/Psl/Str/search_ci.php
  src/Psl/Str/search_last.php
  src/Psl/Str/search_last_ci.php
  src/Psl/Str/slice.php
  src/Psl/Str/splice.php
  src/Psl/Str/split.php
  src/Psl/Str/starts_with.php
  src/Psl/Str/starts_with_ci.php
  src/Psl/Str/strip_prefix.php
  src/Psl/Str/strip_suffix.php
  src/Psl/Str/truncate.php
  src/Psl/Str/uppercase.php
  src/Psl/Str/width.php
  src/Psl/Str/wrap.php
  tests/unit/Str/AfterCiTest.php
  tests/unit/Str/AfterLastCiTest.php
  tests/unit/Str/AfterLastTest.php
  tests/unit/Str/AfterTest.php
  tests/unit/Str/BeforeCiTest.php
  tests/unit/Str/BeforeLastCiTest.php
  tests/unit/Str/BeforeLastTest.php
  tests/unit/Str/BeforeTest.php
Labels: Priority: High, Status: Completed, Type: Enhancement, Type: BC Break

#257 feat(network): introduce network, tcp, and unix components
  CHANGELOG.md
  composer.json
  composer.lock
  config/.phpcs.xml
  docs/README.md
  docs/component/network-tcp.md
  docs/component/network.md
  docs/component/tcp.md
  docs/component/unix.md
  docs/documenter.php
  examples/run.php
  examples/tcp/basic-http-client.php
  examples/tcp/basic-http-server.php
  examples/tcp/concurrent.php
  examples/unix/concurrent.php
  src/Psl/File/WriteMode.php
  src/Psl/IO/Internal/ResourceHandle.php
  src/Psl/Internal/Loader.php
  src/Psl/Network/Address.php
  src/Psl/Network/Exception/AlreadyStoppedException.php
  src/Psl/Network/Exception/ExceptionInterface.php
  src/Psl/Network/Exception/InvalidArgumentException.php
  src/Psl/Network/Exception/RuntimeException.php
  src/Psl/Network/Exception/TimeoutException.php
  src/Psl/Network/Internal/get_peer_name.php
  src/Psl/Network/Internal/get_sock_name.php
  src/Psl/Network/Internal/server_listen.php
  src/Psl/Network/Internal/socket_accept.php
  src/Psl/Network/Internal/socket_connect.php
  src/Psl/Network/ServerInterface.php
  src/Psl/Network/SocketInterface.php
  src/Psl/Network/SocketOptions.php
  src/Psl/Network/SocketScheme.php
  src/Psl/TCP/ConnectOptions.php
  src/Psl/TCP/Internal/Socket.php
  src/Psl/TCP/Server.php
  src/Psl/TCP/ServerOptions.php
  src/Psl/TCP/SocketInterface.php
  src/Psl/TCP/connect.php
  src/Psl/Unix/Internal/Socket.php
  src/Psl/Unix/Internal/socket_accept.php
  src/Psl/Unix/Server.php
  src/Psl/Unix/SocketInterface.php
  src/Psl/Unix/connect.php
  tests/unit/TCP/ConnectTest.php
  tests/unit/TCP/ServerTest.php
  tests/unit/Unix/ConnectTest.php
  tests/unit/Unix/ServerTest.php
Labels: Priority: High, Status: Completed, Type: Enhancement

#262 Call clearstatcache after writing to a file to reset file stat
  src/Psl/Filesystem/Internal/write_file.php
  tests/unit/Filesystem/FileTest.php
Labels: Priority: Medium, Status: Completed, Type: Bug

#264 chore(io/tcp/unix): improve performance, and closed handle/server condition
  docs/component/filesystem.md
  docs/component/tcp.md
  docs/component/unix.md
  examples/tcp/basic-http-server.php
  src/Psl/Filesystem/append_file.php
  src/Psl/Filesystem/write_file.php
  src/Psl/IO/Internal/ResourceHandle.php
  src/Psl/Internal/Loader.php
  src/Psl/Network/Internal/socket_accept.php
  src/Psl/TCP/Server.php
  src/Psl/Unix/Server.php
  tests/unit/IO/PipeTest.php
  tests/unit/TCP/ServerTest.php
  tests/unit/Unix/ServerTest.php
Labels: Priority: High, Status: Completed, Type: Maintenance

#266 ci(unit-tests): test on macos
  .github/workflows/unit-tests.yml
  tests/unit/Async/RunTest.php
Labels: Priority: High, Status: Completed, Type: Maintenance

#267 chore(io): do not throw on non-blocking resource
  docs/component/file.md
  docs/component/io.md
  docs/component/shell.md
  src/Psl/File/Internal/ResourceHandle.php
  src/Psl/File/Internal/open.php
  src/Psl/File/ReadHandle.php
  src/Psl/File/ReadWriteHandle.php
  src/Psl/File/WriteHandle.php
  src/Psl/File/open_read_only.php
  src/Psl/File/open_read_write.php
  src/Psl/File/open_write_only.php
  src/Psl/File/temporary.php
  src/Psl/IO/Exception/BlockingException.php
  src/Psl/IO/Internal/ResourceHandle.php
  src/Psl/IO/Reader.php
  src/Psl/IO/Stream/CloseHandle.php
  src/Psl/IO/Stream/CloseReadHandle.php
  src/Psl/IO/Stream/CloseReadWriteHandle.php
  src/Psl/IO/Stream/CloseSeekHandle.php
  src/Psl/IO/Stream/CloseSeekReadHandle.php
  src/Psl/IO/Stream/CloseSeekReadWriteHandle.php
  src/Psl/IO/Stream/CloseSeekWriteHandle.php
  src/Psl/IO/Stream/CloseWriteHandle.php
  src/Psl/IO/Stream/ReadHandle.php
  src/Psl/IO/Stream/ReadWriteHandle.php
  src/Psl/IO/Stream/SeekHandle.php
  src/Psl/IO/Stream/SeekReadHandle.php
  src/Psl/IO/Stream/SeekReadWriteHandle.php
  src/Psl/IO/Stream/SeekWriteHandle.php
  src/Psl/IO/Stream/WriteHandle.php
  src/Psl/IO/WriteHandleConvenienceMethodsTrait.php
  src/Psl/IO/WriteHandleInterface.php
  src/Psl/IO/pipe.php
  src/Psl/Internal/Loader.php
  src/Psl/Shell/execute.php
  src/Psl/TCP/Internal/Socket.php
  src/Psl/Unix/Internal/Socket.php
Labels: Priority: Critical, Status: Completed, Type: Maintenance, Type: Enhancement

#268 fix: fix windows support
  .github/workflows/unit-tests.yml
  docs/component/io.md
  docs/component/shell.md
  docs/component/unix.md
  src/Psl/Filesystem/create_temporary_file.php
  src/Psl/IO/Reader.php
  src/Psl/IO/pipe.php
  src/Psl/Shell/execute.php
  src/Psl/Unix/Server.php
  src/Psl/Unix/connect.php
  tests/unit/Async/AwaitReadableTest.php
  tests/unit/Env/CurrentExecTest.php
  tests/unit/Filesystem/CopyTest.php
  tests/unit/Filesystem/FileTest.php
  tests/unit/Filesystem/PermissionsTest.php
  tests/unit/Filesystem/ReadDirectoryTest.php
  tests/unit/Shell/EscapeCommandTest.php
  tests/unit/Shell/ExecuteTest.php
  tests/unit/Unix/ConnectTest.php
  tests/unit/Unix/ServerTest.php
Labels: Priority: Critical, Status: Completed, Type: Maintenance, Type: Enhancement

#269 fix(shell): fix windows support
  docs/component/shell.md
  src/Psl/Shell/execute.php
Labels: Priority: Critical, Status: Completed, Type: Enhancement

#270 fix(io): fix readAll() blocks
  examples/io/benchmark.php
  examples/shell/concurrent.php
  examples/unix/concurrent.php
  src/Psl/IO/ReadHandleConvenienceMethodsTrait.php
Labels: Priority: Critical, Status: Completed, Type: Enhancement, Type: Bug

#273 feat(io-stream): add getStream() method to access underlying stream
  docs/component/io-stream.md
  docs/component/io.md
  src/Psl/File/HandleInterface.php
  src/Psl/File/Internal/AbstractHandleWrapper.php
  src/Psl/File/ReadHandleInterface.php
  src/Psl/File/ReadWriteHandleInterface.php
  src/Psl/File/WriteHandleInterface.php
  src/Psl/IO/Internal/ResourceHandle.php
  src/Psl/IO/Stream/CloseHandle.php
  src/Psl/IO/Stream/CloseHandleInterface.php
  src/Psl/IO/Stream/CloseReadHandle.php
  src/Psl/IO/Stream/CloseReadHandleInterface.php
  src/Psl/IO/Stream/CloseReadWriteHandle.php
  src/Psl/IO/Stream/CloseReadWriteHandleInterface.php
  src/Psl/IO/Stream/CloseSeekHandle.php
  src/Psl/IO/Stream/CloseSeekHandleInterface.php
  src/Psl/IO/Stream/CloseSeekReadHandle.php
  src/Psl/IO/Stream/CloseSeekReadHandleInterface.php
  src/Psl/IO/Stream/CloseSeekReadWriteHandle.php
  src/Psl/IO/Stream/CloseSeekReadWriteHandleInterface.php
  src/Psl/IO/Stream/CloseSeekWriteHandle.php
  src/Psl/IO/Stream/CloseSeekWriteHandleInterface.php
  src/Psl/IO/Stream/CloseWriteHandle.php
  src/Psl/IO/Stream/CloseWriteHandleInterface.php
  src/Psl/IO/Stream/HandleInterface.php
  src/Psl/IO/Stream/ReadHandle.php
  src/Psl/IO/Stream/ReadHandleInterface.php
  src/Psl/IO/Stream/ReadWriteHandle.php
  src/Psl/IO/Stream/ReadWriteHandleInterface.php
  src/Psl/IO/Stream/SeekHandle.php
  src/Psl/IO/Stream/SeekHandleInterface.php
  src/Psl/IO/Stream/SeekReadHandle.php
  src/Psl/IO/Stream/SeekReadHandleInterface.php
  src/Psl/IO/Stream/SeekReadWriteHandle.php
  src/Psl/IO/Stream/SeekReadWriteHandleInterface.php
  src/Psl/IO/Stream/SeekWriteHandle.php
  src/Psl/IO/Stream/SeekWriteHandleInterface.php
  src/Psl/IO/Stream/WriteHandle.php
  src/Psl/IO/Stream/WriteHandleInterface.php
  src/Psl/IO/error_handle.php
  src/Psl/IO/input_handle.php
  src/Psl/IO/output_handle.php
  src/Psl/IO/pipe.php
  tests/unit/Async/AwaitReadableTest.php
  tests/unit/Async/RunTest.php
Labels: Priority: High, Status: Completed, Type: Enhancement

#274 chore(io): do not throw already closed exception when closing twice
  src/Psl/File/Internal/AbstractHandleWrapper.php
  src/Psl/File/Internal/ResourceHandle.php
  src/Psl/IO/CloseHandleInterface.php
  src/Psl/IO/Internal/ResourceHandle.php
  src/Psl/TCP/Internal/Socket.php
  src/Psl/Unix/Internal/Socket.php
  tests/unit/File/ReadWriteHandleTest.php
Labels: Priority: High, Status: Completed, Type: Enhancement

#275 chore(internal): relay on autoloading when not using preloading
  composer.json
  composer.lock
  src/Psl/Internal/Loader.php
Labels: Priority: High, Status: Completed, Type: Maintenance, Type: Enhancement

#277 feat(io): queue operations instead of throwing
  examples/io/queued.php
  src/Psl/IO/Internal/ResourceHandle.php
Labels: Priority: Medium, Status: Completed, Type: Enhancement

#278 chore(io): simplify write/read queue implementation
  src/Psl/Async/Awaitable.php
  src/Psl/IO/Internal/ResourceHandle.php
Labels: Priority: High, Status: Completed, Type: Enhancement

#279 feat(udp/tcp): queue operations instead of throwing
  docs/component/io.md
  docs/component/tcp.md
  docs/component/unix.md
  examples/io/benchmark.php
  examples/tcp/basic-http-server.php
  src/Psl/Filesystem/read_file.php
  src/Psl/IO/Internal/ResourceHandle.php
  src/Psl/IO/MemoryHandle.php
  src/Psl/IO/ReadHandleConvenienceMethodsTrait.php
  src/Psl/IO/ReadHandleInterface.php
  src/Psl/IO/Reader.php
  src/Psl/IO/SeekHandleInterface.php
  src/Psl/IO/WriteHandleInterface.php
  src/Psl/TCP/Internal/Socket.php
  src/Psl/TCP/Server.php
  src/Psl/Unix/Internal/Socket.php
  src/Psl/Unix/Server.php
  tests/unit/IO/MemoryHandleTest.php
  tests/unit/TCP/ServerTest.php
  tests/unit/Unix/ServerTest.php
Labels: Priority: High, Status: Completed, Type: Enhancement

#280 chore(async): extend scheduler wrapper
  docs/component/tcp.md
  docs/component/unix.md
  examples/tcp/basic-http-server.php
  src/Psl/Async/Scheduler.php
  src/Psl/Exception/ExceptionInterface.php
  src/Psl/IO/Internal/ResourceHandle.php
  src/Psl/Internal/suppress.php
  src/Psl/Network/Internal/socket_connect.php
  src/Psl/TCP/Server.php
  src/Psl/Unix/Internal/socket_accept.php
  src/Psl/Unix/Server.php
  tests/unit/TCP/ServerTest.php
  tests/unit/Unix/ServerTest.php
Labels: Priority: High, Status: Completed, Type: Enhancement

#283 feat(channel): introduce new channel component
  CHANGELOG.md
  docs/README.md
  docs/component/channel.md
  docs/component/data-structure.md
  docs/documenter.php
  examples/channel/main.php
  src/Psl/Channel/ChannelInterface.php
  src/Psl/Channel/Exception/ClosedChannelException.php
  src/Psl/Channel/Exception/EmptyChannelException.php
  src/Psl/Channel/Exception/ExceptionInterface.php
  src/Psl/Channel/Exception/FullChannelException.php
  src/Psl/Channel/Internal/ChannelState.php
  src/Psl/Channel/Internal/Receiver.php
  src/Psl/Channel/Internal/Sender.php
  src/Psl/Channel/ReceiverInterface.php
  src/Psl/Channel/SenderInterface.php
  src/Psl/Channel/bounded.php
  src/Psl/Channel/unbounded.php
  src/Psl/DataStructure/PriorityQueue.php
  src/Psl/DataStructure/Queue.php
  src/Psl/DataStructure/QueueInterface.php
  src/Psl/Internal/Loader.php
  tests/unit/Channel/BoundedChannelTest.php
  tests/unit/Channel/UnboundedChannelTest.php
Labels: Priority: Medium, Status: Completed, Type: Enhancement

#284 fix(channel): return immediately after cancelling send/recieve callbacks
  src/Psl/Channel/Internal/Receiver.php
  src/Psl/Channel/Internal/Sender.php
Labels: Priority: Medium, Status: Completed, Type: Bug

#285 fix(channel): fix performance issue
  examples/channel/bounded.php
  src/Psl/Channel/Internal/Receiver.php
  src/Psl/Channel/Internal/Sender.php
Labels: Priority: Critical, Status: Completed, Type: Bug

#289 chore(channel): improve performance
  src/Psl/Channel/Internal/ChannelState.php
  src/Psl/Channel/Internal/Receiver.php
  src/Psl/Channel/Internal/Sender.php
  tests/benchmark/Channel/CommunicationBench.php
  tests/benchmark/Type/ArrayKeyTypeBench.php
  tests/benchmark/Type/DictTypeBench.php
  tests/benchmark/Type/IntTypeBench.php
  tests/benchmark/Type/NonEmptyStringTypeBench.php
  tests/benchmark/Type/ShapeTypeBench.php
  tests/benchmark/Type/StringTypeBench.php
  tests/benchmark/Type/VecTypeBench.php
Labels: Priority: Medium, Status: Completed, Type: Enhancement
