Repository azjezz/psl, pull requests merged in 2021-03, with the labels that each got.

#143 [Shell] Introduce shell component
  src/Psl/Internal/Loader.php
  src/Psl/Shell/Exception/ExceptionInterface.php
  src/Psl/Shell/Exception/FailedExecutionException.php
  src/Psl/Shell/Exception/PossibleAttackException.php
  src/Psl/Shell/Exception/RuntimeException.php
  src/Psl/Shell/escape_argument.php
  src/Psl/Shell/escape_command.php
  src/Psl/Shell/execute.php
  tests/Psl/Shell/EscapeArgumentTest.php
  tests/Psl/Shell/EscapeCommandTest.php
  tests/Psl/Shell/Exception/FailedExecutionExceptionTest.php
  tests/Psl/Shell/ExecuteTest.php
Labels: Priority: High, Status: Review Needed, Type: Enhancement

#147 remove composer autoloading
  composer.json
  src/Psl/Internal/Loader.php
Labels: Priority: High, Status: Completed, Type: Maintenance

#149 [Html] Introduce HTML component
  src/Psl/Html/decode.php
  src/Psl/Html/decode_special_characters.php
  src/Psl/Html/encode.php
  src/Psl/Html/encode_special_characters.php
  src/Psl/Internal/Loader.php
  tests/Psl/Html/DecodeSpecialCharactersTest.php
  tests/Psl/Html/DecodeTest.php
  tests/Psl/Html/EncodeSpecialCharactersTest.php
  tests/Psl/Html/EncodeTest.php
Labels: Priority: High, Type: Enhancement

#150 [Html] add strip_tags function
  src/Psl/Html/encode.php
  src/Psl/Html/encode_special_characters.php
  src/Psl/Html/strip_tags.php
  src/Psl/Internal/Loader.php
  tests/Psl/Html/StripTagsTest.php
Labels: Priority: High, Status: Completed, Type: Enhancement

#144 [Filesystem] Introduce filesystem component
  phpunit.xml.dist
  src/Psl/Filesystem/Exception/ExceptionInterface.php
  src/Psl/Filesystem/Exception/RuntimeException.php
  src/Psl/Filesystem/Internal/write_file.php
  src/Psl/Filesystem/append_file.php
  src/Psl/Filesystem/canonicalize.php
  src/Psl/Filesystem/change_group.php
  src/Psl/Filesystem/change_owner.php
  src/Psl/Filesystem/change_permissions.php
  src/Psl/Filesystem/constants.php
  src/Psl/Filesystem/copy.php
  src/Psl/Filesystem/create_directory.php
  src/Psl/Filesystem/create_file.php
  src/Psl/Filesystem/create_hard_link.php
  src/Psl/Filesystem/create_symbolic_link.php
  src/Psl/Filesystem/create_temporary_file.php
  src/Psl/Filesystem/delete_directory.php
  src/Psl/Filesystem/delete_file.php
  src/Psl/Filesystem/exists.php
  src/Psl/Filesystem/file_size.php
  src/Psl/Filesystem/get_access_time.php
  src/Psl/Filesystem/get_basename.php
  src/Psl/Filesystem/get_change_time.php
  src/Psl/Filesystem/get_directory.php
  src/Psl/Filesystem/get_extension.php
  src/Psl/Filesystem/get_filename.php
  src/Psl/Filesystem/get_group.php
  src/Psl/Filesystem/get_inode.php
  src/Psl/Filesystem/get_modification_time.php
  src/Psl/Filesystem/get_owner.php
  src/Psl/Filesystem/get_permissions.php
  src/Psl/Filesystem/is_directory.php
  src/Psl/Filesystem/is_executable.php
  src/Psl/Filesystem/is_file.php
  src/Psl/Filesystem/is_readable.php
  src/Psl/Filesystem/is_symbolic_link.php
  src/Psl/Filesystem/is_writable.php
  src/Psl/Filesystem/read_directory.php
  src/Psl/Filesystem/read_file.php
  src/Psl/Filesystem/read_symbolic_link.php
  src/Psl/Filesystem/write_file.php
  src/Psl/Internal/Loader.php
  src/Psl/Internal/box.php
  src/Psl/Math/maxva.php
  tests/.cache/.gitignore
  tests/Psl/Filesystem/AbstractFilesystemTest.php
  tests/Psl/Filesystem/CopyTest.php
  tests/Psl/Filesystem/FileTest.php
  tests/Psl/Filesystem/LinkTest.php
  tests/Psl/Filesystem/PathTest.php
  tests/Psl/Filesystem/PermissionsTest.php
  tests/Psl/Filesystem/ReadDirectoryTest.php
Labels: Priority: High, Status: Review Needed, Type: Enhancement

#156 split documentation
  docs/README.md
  docs/README.template.md
  docs/component/arr.md
  docs/component/collection.md
  docs/component/data-structure.md
  docs/component/dict.md
  docs/component/encoding-base64.md
  docs/component/encoding-hex.md
  docs/component/env.md
  docs/component/filesystem.md
  docs/component/fun.md
  docs/component/hash.md
  docs/component/html.md
  docs/component/iter.md
  docs/component/json.md
  docs/component/math.md
  docs/component/observer.md
  docs/component/password.md
  docs/component/pseudo-random.md
  docs/component/psl.md
  docs/component/regex.md
  docs/component/result.md
  docs/component/secure-random.md
  docs/component/shell.md
  docs/component/str-byte.md
  docs/component/str-grapheme.md
  docs/component/str.md
  docs/component/type.md
  docs/component/vec.md
  docs/documenter.php
  docs/templates/README.template.md
  docs/templates/component.template.md
  src/Psl/Internal/Loader.php
Labels: Priority: Medium, Status: Review Needed, Type: Documentation, Type: Enhancement

#158 don't run IO tests on windows.
  docs/component/env.md
  src/Psl/Env/current_exec.php
  tests/Psl/Env/CurrentExecTest.php
  tests/Psl/Filesystem/AbstractFilesystemTest.php
  tests/Psl/Filesystem/LinkTest.php
  tests/Psl/IOTestCase.php
  tests/Psl/Shell/EscapeArgumentTest.php
  tests/Psl/Shell/EscapeCommandTest.php
  tests/Psl/Shell/ExecuteTest.php
Labels: Priority: High, Status: In Progress

#127 [IO] Introduce IO component
  docs/README.md
  docs/component/io.md
  docs/documenter.php
  src/Psl/IO/CloseHandle.php
  src/Psl/IO/CloseReadHandle.php
  src/Psl/IO/CloseReadWriteHandle.php
  src/Psl/IO/CloseSeekHandle.php
  src/Psl/IO/CloseSeekReadHandle.php
  src/Psl/IO/CloseSeekReadWriteHandle.php
  src/Psl/IO/CloseSeekWriteHandle.php
  src/Psl/IO/CloseWriteHandle.php
  src/Psl/IO/Exception/AlreadyClosedException.php
  src/Psl/IO/Exception/BlockingException.php
  src/Psl/IO/Exception/ExceptionInterface.php
  src/Psl/IO/Exception/RuntimeException.php
  src/Psl/IO/Handle.php
  src/Psl/IO/Internal/ReadOnlyHandleDecorator.php
  src/Psl/IO/Internal/ResourceHandle.php
  src/Psl/IO/Internal/WriteOnlyHandleDecorator.php
  src/Psl/IO/Internal/open.php
  src/Psl/IO/MemoryHandle.php
  src/Psl/IO/ReadHandle.php
  src/Psl/IO/ReadWriteHandle.php
  src/Psl/IO/Reader.php
  src/Psl/IO/SeekHandle.php
  src/Psl/IO/SeekReadHandle.php
  src/Psl/IO/SeekReadWriteHandle.php
  src/Psl/IO/SeekWriteHandle.php
  src/Psl/IO/WriteHandle.php
  src/Psl/IO/Writer.php
  src/Psl/IO/error_handle.php
  src/Psl/IO/input_handle.php
  src/Psl/IO/output_handle.php
  src/Psl/Internal/Loader.php
  src/Psl/Internal/suppress.php
  src/Psl/Regex/Internal/call_preg.php
  tests/Psl/IO/MemoryHandleTest.php
  tests/Psl/IO/ReaderTest.php
Labels: Priority: Medium, Status: In Progress, Status: Revision Needed, Type: Enhancement

#159 improve metaphone errors
  docs/component/str.md
  src/Psl/Str/metaphone.php
  tests/Psl/Str/MetaphoneTest.php
Labels: Priority: Medium, Status: Completed, Type: BC Break, Type: Enhancement

#160 [Str][Byte] simplify reverse implementation
  docs/component/str-byte.md
  src/Psl/Str/Byte/reverse.php
Labels: Priority: Medium, Status: Completed, Type: Enhancement

#163 fix psalm issues
  docs/component/arr.md
  docs/component/dict.md
  docs/component/env.md
  docs/component/iter.md
  psalm.xml
  src/Psl/Arr/first.php
  src/Psl/Arr/firstx.php
  src/Psl/Arr/last.php
  src/Psl/Arr/lastx.php
  src/Psl/Arr/merge.php
  src/Psl/Collection/Map.php
  src/Psl/Collection/MutableMap.php
  src/Psl/DataStructure/PriorityQueue.php
  src/Psl/Dict/count_values.php
  src/Psl/Dict/filter_with_key.php
  src/Psl/Dict/merge.php
  src/Psl/Dict/sort_by.php
  src/Psl/Dict/unique_by.php
  src/Psl/Env/get_var.php
  src/Psl/Env/join_paths.php
  src/Psl/Hash/Context.php
  src/Psl/Iter/contains_key.php
  src/Psl/Iter/count.php
  src/Psl/Iter/filter_with_key.php
  src/Psl/Iter/merge.php
  src/Psl/Iter/random.php
  src/Psl/Iter/reduce_keys.php
  src/Psl/Iter/zip.php
  src/Psl/Math/base_convert.php
  src/Psl/Math/from_base.php
  src/Psl/Math/maxva.php
  src/Psl/Math/median.php
  src/Psl/PseudoRandom/float.php
  src/Psl/SecureRandom/float.php
  src/Psl/Str/chr.php
  src/Psl/Type/Internal/IntersectionType.php
  src/Psl/Type/Internal/IterableType.php
  src/Psl/Type/Internal/MutableMapType.php
  src/Psl/Vec/filter_with_key.php
  src/Psl/Vec/keys.php
Labels: Priority: High, Status: In Progress, Type: Bug, Type: Enhancement

#162 use non-empty-string annoation
  docs/component/math.md
  docs/component/str-byte.md
  docs/component/str.md
  src/Psl/Math/base_convert.php
  src/Psl/Math/from_base.php
  src/Psl/Str/Byte/pad_left.php
  src/Psl/Str/Byte/pad_right.php
  src/Psl/Str/pad_left.php
  src/Psl/Str/pad_right.php
  src/Psl/Str/wrap.php
Labels: Priority: Medium, Status: Accepted, Type: Enhancement

#155 replace `@use` annotation by `@see`
  docs/component/arr.md
  src/Psl/Arr/sort_by_key.php
Labels: Priority: Medium, Status: Completed, Type: Enhancement

#168 Dict\unique_scalar() function to avoid performance penalty hit when using Dict\unique() on large scalar arrays
  docs/component/dict.md
  src/Psl/Dict/unique_scalar.php
  src/Psl/Internal/Loader.php
  tests/Psl/Dict/UniqueScalarTest.php
Labels: Priority: High, Status: Revision Needed, Type: Enhancement

#170 recommand using the psalm-plugin package over builtin integration
  README.md
  composer.json
  integration/Psalm/Plugin.php
Labels: Priority: High, Status: Completed, Type: Enhancement

#176 remove usage of closure generics.
  src/Psl/Dict/diff.php
  src/Psl/Dict/diff_by_key.php
  src/Psl/Dict/intersect.php
  src/Psl/Dict/intersect_by_key.php
  src/Psl/Fun/pipe.php
Labels: Priority: High, Status: Completed, Type: Enhancement
