Repository azjezz/psl, pull requests merged in 2021-04, with the labels that each got.

#177 Added positive int as type
  docs/component/type.md
  src/Psl/Internal/Loader.php
  src/Psl/Type/Internal/PositiveIntType.php
  src/Psl/Type/positive_int.php
  tests/Psl/Type/PositiveIntTypeTest.php
Labels: Priority: Medium, Status: Completed, Type: Enhancement

#151 [Regex] Introduce *_match() functions to fetch captured data groups
  docs/component/json.md
  docs/component/regex.md
  integration/Psalm/Plugin.php
  src/Psl/Internal/Loader.php
  src/Psl/Json/typed.php
  src/Psl/Regex/capture_groups.php
  src/Psl/Regex/every_match.php
  src/Psl/Regex/first_match.php
  tests/Psl/Regex/CaptureGroupsTest.php
  tests/Psl/Regex/EveryMatchTest.php
  tests/Psl/Regex/FirstMatchTest.php
Labels: Priority: High, Status: Completed, Type: Enhancement

#185 Feature/variadic intersection type
  docs/component/type.md
  src/Psl/Type/intersection.php
  tests/static-analysis/Type/intersection.php
  tests/unit/Type/IntersectionTypeTest.php
Labels: Priority: Medium, Status: Accepted, Status: Revision Needed, Type: Enhancement
