Repository azjezz/psl, pull requests merged in 2021-05, with the labels that each got.

#196 fix strict type ignored when mapping or filtering arrays
  docs/component/vec.md
  src/Psl/Dict/filter.php
  src/Psl/Dict/filter_keys.php
  src/Psl/Iter/contains_key.php
  src/Psl/Vec/filter.php
  src/Psl/Vec/filter_keys.php
  src/Psl/Vec/filter_nulls.php
  src/Psl/Vec/filter_with_key.php
  src/Psl/Vec/map.php
  tests/Psl/Dict/MapTest.php
  tests/Psl/Vec/FilterKeysTest.php
  tests/Psl/Vec/FilterWithKeyTest.php
  tests/Psl/Vec/MapTest.php
Labels: Priority: High, Status: Completed, Type: Bug

#197 Fixed mismatching psalm assert variables
  src/Psl/Class/defined.php
  src/Psl/Class/exists.php
  src/Psl/Iter/is_empty.php
Labels: Priority: Medium, Status: Completed, Type: Bug

#202 [Type] correct vec string
  src/Psl/Type/Internal/VecType.php
  tests/unit/Type/ShapeAllowUnknownFieldsTypeTest.php
  tests/unit/Type/ShapeTypeTest.php
  tests/unit/Type/UnionTypeTest.php
  tests/unit/Type/VecTypeTest.php
Labels: Priority: High, Status: Completed, Type: Enhancement

#200 [Type] add non_empty_vec
  docs/component/type.md
  src/Psl/Internal/Loader.php
  src/Psl/Type/Internal/NonEmptyVecType.php
  src/Psl/Type/non_empty_vec.php
  tests/unit/Type/NonEmptyVecTypeTest.php
Labels: Priority: Medium, Status: Revision Needed, Type: Enhancement

#201 [Type] add non_empty_dict
  docs/component/type.md
  src/Psl/Internal/Loader.php
  src/Psl/Type/Internal/NonEmptyDictType.php
  src/Psl/Type/non_empty_dict.php
  tests/unit/Type/NonEmptyDictTypeTest.php
Labels: Priority: Medium, Status: Completed, Type: Enhancement

#203 [Type] correct dict string
  src/Psl/Type/Internal/DictType.php
  tests/unit/Type/DictTypeTest.php
Labels: Priority: Medium, Status: Completed, Type: Enhancement
