Repository azjezz/psl, pull requests merged in 2021-07, with the labels that each got.

#217 Suggest Psalm plugin
  composer.json
Labels: Priority: Medium, Status: Accepted, Type: Enhancement

#218 Fixed example of Vec\reproduce()
  src/Psl/Vec/reproduce.php
Labels: Priority: Low, Status: Completed, Type: Documentation, Type: Enhancement

#215 [Fun] Add lazy() for doing lazy evaluations
  docs/component/fun.md
  src/Psl/Fun/Internal/LazyEvaluator.php
  src/Psl/Fun/lazy.php
  src/Psl/Internal/Loader.php
  tests/unit/Fun/LazyTest.php
Labels: Priority: Medium, Status: Accepted, Type: Enhancement

#193 [RandomSequence] Introduce random sequence component
  docs/README.md
  docs/component/psl.md
  docs/component/random-sequence.md
  docs/component/secure-random.md
  docs/documenter.php
  src/Psl/Internal/Loader.php
  src/Psl/RandomSequence/Internal/MersenneTwisterTrait.php
  src/Psl/RandomSequence/MersenneTwisterPHPVariantSequence.php
  src/Psl/RandomSequence/MersenneTwisterSequence.php
  src/Psl/RandomSequence/SecureSequence.php
  src/Psl/RandomSequence/SequenceInterface.php
  src/Psl/SecureRandom/int.php
  src/Psl/sequence.php
  tests/unit/RandomSequence/MersenneTwisterPHPVariantSequenceTest.php
  tests/unit/RandomSequence/MersenneTwisterSequenceTest.php
Labels: Experimental, Priority: Medium, Status: In Progress, Type: Enhancement

#219 [Regex] Fix replace_with() signature
  src/Psl/Regex/replace_with.php
Labels: Priority: Medium, Status: Completed, Type: Enhancement

#220 Don't perform operations on possible numeric-string
  src/Psl/Math/mean.php
  src/Psl/Math/sum_floats.php
Labels: Priority: High, Status: Accepted, Type: Enhancement
