Repository azjezz/psl, pull requests merged in 2021-12, with the labels that each got.

#290 chore(shell): use exec to avoid spawning a grandchild process
  src/Psl/Shell/execute.php
  tests/unit/Shell/ExecuteTest.php
Labels: Priority: High, Status: Completed, Type: Maintenance, Type: Enhancement

#291 feat(async): introduce more async helper functions
  docs/component/async.md
  examples/async/usleep.php
  examples/io/pipe.php
  examples/shell/concurrent.php
  examples/tcp/concurrent.php
  examples/unix/concurrent.php
  src/Psl/Async/all.php
  src/Psl/Async/any.php
  src/Psl/Async/concurrent.php
  src/Psl/Async/first.php
  src/Psl/Async/parallel.php
  src/Psl/Async/reflect.php
  src/Psl/Async/series.php
  src/Psl/Async/wrap.php
  src/Psl/Internal/Loader.php
  src/Psl/Shell/execute.php
  tests/unit/Async/AllTest.php
  tests/unit/Async/ParallelTest.php
  tests/unit/Async/ReflectTest.php
  tests/unit/Async/RunTest.php
  tests/unit/Async/SeriesTest.php
  tests/unit/Async/WrapTest.php
  tests/unit/IO/PipeTest.php
  tests/unit/TCP/ConnectTest.php
  tests/unit/TCP/ServerTest.php
  tests/unit/Unix/ConnectTest.php
  tests/unit/Unix/ServerTest.php
Labels: Priority: Medium, Status: Completed, Type: Enhancement

#292 chore(shell): improve type coverage
  src/Psl/Shell/execute.php
Labels: Priority: Medium, Status: Completed, Type: Enhancement

#294 chore(channel): improve performance
  examples/channel/bounded.php
  src/Psl/Channel/Internal/ChannelState.php
  src/Psl/Channel/Internal/Receiver.php
  src/Psl/Channel/Internal/Sender.php
  tests/unit/Channel/BoundedChannelTest.php
Labels: Priority: Medium, Status: Completed, Type: Enhancement

#295 chore(async): run event loop on main();
  src/Psl/Async/main.php
Labels: Priority: Medium, Status: Completed, Type: Enhancement

#296 fix(io): do not throw on close.
  src/Psl/IO/Internal/ResourceHandle.php
Labels: Priority: Critical, Status: Completed, Type: Bug

#297 feat(io): introduce write(), write_line(), write_error(), and write_error_line() functions
  CHANGELOG.md
  docs/component/io.md
  examples/async/usleep.php
  examples/channel/bounded.php
  examples/channel/main.php
  examples/io/benchmark.php
  examples/io/pipe.php
  examples/io/queued.php
  examples/run.php
  examples/shell/concurrent.php
  examples/shell/main.php
  examples/shell/timeout.php
  examples/tcp/basic-http-client.php
  examples/tcp/basic-http-server.php
  examples/tcp/concurrent.php
  examples/unix/concurrent.php
  src/Psl/IO/write.php
  src/Psl/IO/write_error.php
  src/Psl/IO/write_error_line.php
  src/Psl/IO/write_line.php
  src/Psl/Internal/Loader.php
  src/Psl/TCP/Server.php
Labels: Priority: Medium, Status: Completed, Type: Enhancement

#298 feat(html): use Str\Encoding instead of string|null for $encoding argument
  CHANGELOG.md
  src/Psl/Html/decode.php
  src/Psl/Html/encode.php
  src/Psl/Html/encode_special_characters.php
  tests/unit/Html/DecodeTest.php
  tests/unit/Html/EncodeSpecialCharactersTest.php
  tests/unit/Html/EncodeTest.php
Labels: Priority: Medium, Status: Completed, Type: Enhancement, Type: BC Break

#304 chore(php): fix PHP 8.1 deprecations
  .github/workflows/unit-tests.yml
  Makefile
  composer.json
  src/Psl/Internal/internal_encoding.php
  src/Psl/Iter/Iterator.php
  tests/Psl/Str/WidthTest.php
Labels: Priority: Critical, Status: Completed, Type: Maintenance

#305 chore(async): remove `await_readable`, `await_writable`, `await_signal`, and `wrap` functions
  composer.lock
  docs/component/async.md
  src/Psl/Async/all.php
  src/Psl/Async/await_readable.php
  src/Psl/Async/await_signal.php
  src/Psl/Async/await_writable.php
  src/Psl/Async/parallel.php
  src/Psl/Async/wrap.php
  src/Psl/Internal/Loader.php
  src/Psl/Shell/execute.php
  tests/unit/Async/AwaitReadableTest.php
  tests/unit/Async/WrapTest.php
Labels: Priority: High, Status: Completed, Type: Maintenance

#311 fix(composer): add `Psl` namespace mapped to `src/Psl`
  composer.json
Labels: Priority: High, Status: Completed, Type: Bug

#313 chore(network,tcp,udp): implement socket server, and socket
  docs/component/network.md
  docs/component/tcp.md
  docs/component/unix.md
  examples/tcp/basic-http-server.php
  examples/tcp/concurrent.php
  examples/unix/concurrent.php
  src/Psl/Internal/Loader.php
  src/Psl/Network/Internal/Socket.php
  src/Psl/Network/ServerInterface.php
  src/Psl/Network/StreamServerInterface.php
  src/Psl/Network/StreamSocketInterface.php
  src/Psl/TCP/Server.php
  src/Psl/TCP/SocketInterface.php
  src/Psl/TCP/connect.php
  src/Psl/Unix/Internal/Socket.php
  src/Psl/Unix/Server.php
  src/Psl/Unix/SocketInterface.php
  src/Psl/Unix/connect.php
  tests/unit/TCP/ConnectTest.php
  tests/unit/TCP/ServerTest.php
  tests/unit/Unix/ConnectTest.php
  tests/unit/Unix/ServerTest.php
Labels: Priority: Medium, Status: Completed, Type: Enhancement

#314 chore(io): rename `readImmediately` to `tryRead`, and `writeImmediately` to `tryWrite`
  src/Psl/File/ReadHandle.php
  src/Psl/File/ReadWriteHandle.php
  src/Psl/File/WriteHandle.php
  src/Psl/IO/Internal/ResourceHandle.php
  src/Psl/IO/MemoryHandle.php
  src/Psl/IO/ReadHandleInterface.php
  src/Psl/IO/Reader.php
  src/Psl/IO/Stream/CloseReadHandle.php
  src/Psl/IO/Stream/CloseReadWriteHandle.php
  src/Psl/IO/Stream/CloseSeekReadHandle.php
  src/Psl/IO/Stream/CloseSeekReadWriteHandle.php
  src/Psl/IO/Stream/CloseSeekWriteHandle.php
  src/Psl/IO/Stream/CloseWriteHandle.php
  src/Psl/IO/Stream/ReadHandle.php
  src/Psl/IO/Stream/ReadWriteHandle.php
  src/Psl/IO/Stream/SeekReadHandle.php
  src/Psl/IO/Stream/SeekReadWriteHandle.php
  src/Psl/IO/Stream/SeekWriteHandle.php
  src/Psl/IO/Stream/WriteHandle.php
  src/Psl/IO/WriteHandleInterface.php
  src/Psl/Network/Internal/Socket.php
  tests/unit/File/ReadHandleTest.php
  tests/unit/File/ReadWriteHandleTest.php
  tests/unit/File/WriteHandleTest.php
  tests/unit/IO/MemoryHandleTest.php
  tests/unit/IO/PipeTest.php
  tests/unit/IO/ReaderTest.php
  tests/unit/IO/StreamTest.php
  tests/unit/TCP/ServerTest.php
  tests/unit/Unix/ServerTest.php
Labels: Priority: High, Status: Completed, Type: Enhancement

#286 chore: enable mutation tests
  .github/workflows/mutation-tests.yml
  .gitignore
  Makefile
  composer.json
  composer.lock
  config/infection.json.dist
  config/phpunit.xml.dist
  tests/unit/Async/RunTest.php
  var/.gitignore
Labels: Priority: Medium, Status: Completed, Type: Enhancement

#317 chore: remove type verification at runtime
  config/psalm.xml
  docs/component/channel.md
  docs/component/class.md
  docs/component/file.md
  docs/component/math.md
  docs/component/regex.md
  docs/component/str-byte.md
  docs/component/str.md
  src/Psl/Async/Internal/AwaitableIterator.php
  src/Psl/Channel/Internal/ChannelState.php
  src/Psl/Channel/bounded.php
  src/Psl/Class/has_constant.php
  src/Psl/Class/has_method.php
  src/Psl/Class/is_abstract.php
  src/Psl/Class/is_final.php
  src/Psl/File/ReadWriteHandle.php
  src/Psl/File/WriteHandle.php
  src/Psl/File/temporary.php
  src/Psl/Filesystem/create_temporary_file.php
  src/Psl/IO/Internal/ResourceHandle.php
  src/Psl/IO/MemoryHandle.php
  src/Psl/IO/Reader.php
  src/Psl/IO/WriteHandleInterface.php
  src/Psl/Internal/validate_offset.php
  src/Psl/Iter/Iterator.php
  src/Psl/Math/base_convert.php
  src/Psl/Math/from_base.php
  src/Psl/Math/to_base.php
  src/Psl/Network/Internal/get_peer_name.php
  src/Psl/Network/Internal/get_sock_name.php
  src/Psl/Regex/replace.php
  src/Psl/Regex/replace_every.php
  src/Psl/Regex/replace_with.php
  src/Psl/Str/Byte/pad_left.php
  src/Psl/Str/Byte/pad_right.php
  src/Psl/Str/length.php
  src/Psl/Str/pad_left.php
  src/Psl/Str/pad_right.php
  src/Psl/Str/search.php
  src/Psl/Str/search_ci.php
  src/Psl/Str/search_last.php
  src/Psl/Str/search_last_ci.php
  src/Psl/Str/slice.php
  src/Psl/Str/splice.php
  src/Psl/Str/split.php
  src/Psl/Str/strip_prefix.php
  src/Psl/Str/strip_suffix.php
  src/Psl/Str/wrap.php
  src/Psl/Unix/Server.php
  tests/unit/Channel/BoundedChannelTest.php
  tests/unit/Fun/LazyTest.php
  tests/unit/Math/FromBaseTest.php
  tests/unit/Math/ToBaseTest.php
  tests/unit/Str/SliceTest.php
Labels: Status: Accepted, Status: Completed, Type: Enhancement, Type: BC Break

#318 chore(iter): optimize iterator
  docs/component/iter.md
  src/Psl/Iter/Iterator.php
  src/Psl/Iter/is_empty.php
  tests/unit/Iter/IteratorTest.php
Labels: Priority: High, Status: Completed, Type: Enhancement

#321 chore(collection): throw out-of-bounds exception instead of invariant violation for invalid offset
  CHANGELOG.md
  docs/component/collection.md
  docs/component/dict.md
  src/Psl/Collection/AccessibleCollectionInterface.php
  src/Psl/Collection/CollectionInterface.php
  src/Psl/Collection/Exception/ExceptionInterface.php
  src/Psl/Collection/Exception/OutOfBoundsException.php
  src/Psl/Collection/IndexAccessInterface.php
  src/Psl/Collection/Map.php
  src/Psl/Collection/MapInterface.php
  src/Psl/Collection/MutableAccessibleCollectionInterface.php
  src/Psl/Collection/MutableCollectionInterface.php
  src/Psl/Collection/MutableMap.php
  src/Psl/Collection/MutableMapInterface.php
  src/Psl/Collection/MutableVector.php
  src/Psl/Collection/MutableVectorInterface.php
  src/Psl/Collection/Vector.php
  src/Psl/Collection/VectorInterface.php
  src/Psl/DataStructure/Stack.php
  src/Psl/Dict/drop.php
  src/Psl/Dict/slice.php
  src/Psl/Dict/take.php
  src/Psl/Internal/Loader.php
  tests/unit/Collection/AbstractMapTest.php
  tests/unit/Collection/AbstractVectorTest.php
  tests/unit/Collection/MutableMapTest.php
  tests/unit/Collection/MutableVectorTest.php
  tests/unit/Dict/TakeTest.php
Labels: Priority: High, Status: Completed, Type: Enhancement, Type: BC Break

#322 chore(collection): improve performance
  docs/component/collection.md
  src/Psl/Collection/AccessibleCollectionInterface.php
  src/Psl/Collection/CollectionInterface.php
  src/Psl/Collection/Map.php
  src/Psl/Collection/MapInterface.php
  src/Psl/Collection/MutableAccessibleCollectionInterface.php
  src/Psl/Collection/MutableCollectionInterface.php
  src/Psl/Collection/MutableIndexAccessInterface.php
  src/Psl/Collection/MutableMap.php
  src/Psl/Collection/MutableMapInterface.php
  src/Psl/Collection/MutableVector.php
  src/Psl/Collection/MutableVectorInterface.php
  src/Psl/Collection/Vector.php
  src/Psl/Collection/VectorInterface.php
  src/Psl/Dict/filter_with_key.php
  tests/unit/Collection/AbstractMapTest.php
  tests/unit/Collection/AbstractVectorTest.php
  tests/unit/Collection/MapTest.php
  tests/unit/Collection/MutableMapTest.php
  tests/unit/Collection/MutableVectorTest.php
Labels: Priority: High, Status: Completed, Type: Enhancement

#324 feat(async): introduce semaphore
  docs/component/async.md
  src/Psl/Async/Semaphore.php
  src/Psl/Internal/Loader.php
  tests/unit/Async/SemaphoreTest.php
Labels: Priority: Medium, Status: Accepted, Status: Completed, Type: Enhancement

#325 chore(data-structure): rework exceptions
  CHANGELOG.md
  docs/component/data-structure.md
  src/Psl/DataStructure/Exception/ExceptionInterface.php
  src/Psl/DataStructure/Exception/UnderflowException.php
  src/Psl/DataStructure/PriorityQueue.php
  src/Psl/DataStructure/Queue.php
  src/Psl/DataStructure/QueueInterface.php
  src/Psl/DataStructure/Stack.php
  src/Psl/DataStructure/StackInterface.php
  src/Psl/Exception/UnderflowException.php
  src/Psl/Internal/Loader.php
  tests/unit/DataStructure/PriorityQueueTest.php
  tests/unit/DataStructure/QueueTest.php
  tests/unit/DataStructure/StackTest.php
  tests/unit/Dict/TakeTest.php
Labels: Priority: High, Status: Accepted, Status: Review Needed, Type: Enhancement, Type: BC Break
