Repository azjezz/psl, pull requests merged in 2021-02, with the labels that each got.

#116 [Type] add non-empty-string type
  src/Psl/Internal/Loader.php
  src/Psl/Iter/flat_map.php
  src/Psl/Type/Internal/NonEmptyStringType.php
  src/Psl/Type/non_empty_string.php
  tests/Psl/Type/NonEmptyStringTypeTest.php
Labels: Priority: Medium, Status: Accepted, Type: Enhancement

#117 [Type] fix parameters name in union function.
  src/Psl/Type/union.php
Labels: Priority: High, Status: Accepted, Type: Bug, Type: Enhancement

#119 [Type] add shape
  README.md
  composer.json
  psalm.xml
  src/Psl/Internal/Loader.php
  src/Psl/Internal/Psalm/EventHandler/ShapeFunctionReturnTypeProvider.php
  src/Psl/Internal/Psalm/Plugin.php
  src/Psl/Type/Exception/TypeTrace.php
  src/Psl/Type/Internal/ShapeType.php
  src/Psl/Type/shape.php
  tests/Psl/Type/ShapeTypeTest.php
Labels: Priority: High, Status: Review Needed, Type: Enhancement

#124 [Arr] deprecate duplicated functions
  src/Psl/Arr/at.php
  src/Psl/Arr/contains.php
  src/Psl/Arr/contains_key.php
  src/Psl/Arr/count.php
  src/Psl/Arr/count_values.php
  src/Psl/Arr/fill.php
  src/Psl/Arr/filter_nulls.php
  src/Psl/Arr/first.php
  src/Psl/Arr/first_key.php
  src/Psl/Arr/firstx.php
  src/Psl/Arr/flat_map.php
  src/Psl/Arr/flatten.php
  src/Psl/Arr/flip.php
  src/Psl/Arr/group_by.php
  src/Psl/Arr/idx.php
  src/Psl/Arr/keys.php
  src/Psl/Arr/last.php
  src/Psl/Arr/last_key.php
  src/Psl/Arr/lastx.php
  src/Psl/Arr/random.php
  src/Psl/Arr/select_keys.php
  src/Psl/Collection/Map.php
  src/Psl/Collection/MutableMap.php
  src/Psl/Collection/MutableVector.php
  src/Psl/Collection/Vector.php
  src/Psl/DataStructure/PriorityQueue.php
  src/Psl/DataStructure/Queue.php
  src/Psl/DataStructure/Stack.php
  src/Psl/Dict/count_values.php
  src/Psl/Dict/equal.php
  src/Psl/Hash/Context.php
  src/Psl/Internal/Loader.php
  src/Psl/Iter/Iterator.php
  src/Psl/Iter/enumerate.php
  src/Psl/Iter/product.php
  src/Psl/Iter/random.php
  src/Psl/Password/hash.php
  src/Psl/Type/Internal/ShapeType.php
  src/Psl/Vec/enumerate.php
  tests/Psl/Arr/RandomTest.php
  tests/Psl/Dict/MapTest.php
  tests/Psl/Vec/EnumerateTest.php
Labels: Priority: High, Status: In Progress, Type: Maintenance

#125 move psalm integration to integration directory
  README.md
  composer.json
  integration/Psalm/EventHandler/ShapeFunctionReturnTypeProvider.php
  integration/Psalm/Plugin.php
  psalm.xml
Labels: Priority: High, Status: Accepted, Type: Enhancement

#56 [Encoding] introduce encoding component
  src/Psl/Encoding/Base64/decode.php
  src/Psl/Encoding/Base64/encode.php
  src/Psl/Encoding/Exception/ExceptionInterface.php
  src/Psl/Encoding/Exception/IncorrectPaddingException.php
  src/Psl/Encoding/Exception/RangeException.php
  src/Psl/Encoding/Hex/decode.php
  src/Psl/Encoding/Hex/encode.php
  src/Psl/Internal/Loader.php
  src/Psl/Internal/validate_offset.php
  src/Psl/Internal/validate_offset_lower_bound.php
  tests/Psl/Encoding/Base64Test.php
  tests/Psl/Encoding/HexTest.php
Labels: Priority: Medium, Status: In Progress, Type: Enhancement, hacktoberfest

#126 Fix the name of the psalm plugin class in the readme
  README.md
Labels: Priority: Medium, Status: Completed, Type: Documentation

#133 Point phpunit to local xsd
  phpunit.xml.dist
Labels: Status: Completed, Type: Enhancement

#134 don't use branch name for badges
  README.md
Labels: Status: Completed, Type: Maintenance

#135 [Regex] Introduce Regex component
  src/Psl/Internal/Loader.php
  src/Psl/Internal/suppress.php
  src/Psl/Regex/Exception/ExceptionInterface.php
  src/Psl/Regex/Exception/InvalidPatternException.php
  src/Psl/Regex/Exception/RuntimeException.php
  src/Psl/Regex/Internal/call_preg.php
  src/Psl/Regex/Internal/get_prec_error.php
  src/Psl/Regex/matches.php
  src/Psl/Regex/replace.php
  src/Psl/Regex/replace_every.php
  src/Psl/Regex/split.php
  src/Psl/Result/Failure.php
  src/Psl/Result/ResultInterface.php
  src/Psl/Result/Success.php
  tests/Psl/Regex/MatchesTest.php
  tests/Psl/Regex/ReplaceEveryTest.php
  tests/Psl/Regex/ReplaceTest.php
  tests/Psl/Regex/SplitTest.php
Labels: Priority: Medium, Status: Completed, Type: Enhancement

#137 [Dict] add intersect and diff functions
  src/Psl/Dict/diff.php
  src/Psl/Dict/diff_by_key.php
  src/Psl/Dict/intersect.php
  src/Psl/Dict/intersect_by_key.php
  src/Psl/Internal/Loader.php
  src/Psl/Iter/chain.php
  src/Psl/Iter/diff_by_key.php
  tests/Psl/Dict/DiffByKeyTest.php
  tests/Psl/Dict/DiffTest.php
  tests/Psl/Dict/IntersectByKeyTest.php
  tests/Psl/Dict/IntersectTest.php
Labels: Priority: Medium, Status: Completed, Type: Enhancement

#139 [Json] use TypeInterface
  src/Psl/Json/typed.php
Labels: Priority: Critical, Status: Completed, Type: Bug
