Repository azjezz/psl, pull requests merged in 2022-11, with the labels that each got.

#367 fix(type): add more valid float coerceings
  src/Psl/Type/Internal/FloatType.php
  tests/unit/Type/FloatTypeTest.php
  tests/unit/Type/NumTypeTest.php
Labels: Priority: High, Status: Accepted, Status: Revision Needed, Type: Enhancement

#364 Use array_is_list for vec types
  src/Psl/Type/Internal/VecType.php
Labels: Priority: High, Status: Accepted, Status: Completed, Type: Enhancement

#362 Add mixed dict and vec types
  docs/component/type.md
  src/Psl/Internal/Loader.php
  src/Psl/Type/Internal/MixedDictType.php
  src/Psl/Type/Internal/MixedVecType.php
  src/Psl/Type/mixed_dict.php
  src/Psl/Type/mixed_vec.php
  tests/unit/Type/MixedDictTypeTest.php
  tests/unit/Type/MixedVecTypeTest.php
  tests/unit/Type/TypeTest.php
Labels: Priority: Medium, Status: Accepted, Status: Revision Needed, Type: Enhancement

#356 feat(option): introduce option component
  composer.lock
  src/Psl/Internal/Loader.php
  src/Psl/Option/Exception/ExceptionInterface.php
  src/Psl/Option/Exception/NoneException.php
  src/Psl/Option/Option.php
  src/Psl/Option/none.php
  src/Psl/Option/some.php
  tests/unit/Option/NoneTest.php
  tests/unit/Option/SomeTest.php
Labels: Priority: Medium, Status: Accepted, Status: Completed, Type: Enhancement, Experimental
