Repository azjezz/psl, pull requests merged in 2022-02, with the labels that each got.

#336 [Result] Collect stats from result sets
  docs/component/result.md
  src/Psl/Internal/Loader.php
  src/Psl/Result/Stats.php
  src/Psl/Result/collect_stats.php
  tests/unit/Result/CollectStatsTest.php
  tests/unit/Result/StatsTest.php
Labels: Priority: Medium, Status: Completed, Status: In Progress, Type: Enhancement

#337 Backport static analysis fixes to 1.6
  src/Psl/Iter/is_empty.php
  src/Psl/Math/mean.php
  src/Psl/Math/sum_floats.php
  src/Psl/Regex/replace_with.php
  src/Psl/Str/Byte/words.php
  src/Psl/Type/Type.php
  src/Psl/Type/TypeInterface.php
  tests/Psl/Dict/UniqueScalarTest.php
  tests/Psl/Iter/ContainsTest.php
  tests/Psl/Math/MinTest.php
  tests/Psl/Math/RoundTest.php
  tests/Psl/Math/SinTest.php
  tests/Psl/Math/SqrtTest.php
  tests/Psl/Math/TanTest.php
  tests/Psl/Math/ToBaseTest.php
  tests/Psl/Str/Byte/SearchCiTest.php
  tests/Psl/Str/Byte/SearchLastTest.php
  tests/Psl/Str/Byte/SearchTest.php
  tests/Psl/Str/Byte/SliceTest.php
  tests/Psl/Str/Byte/StartsWithTest.php
  tests/Psl/Str/Byte/TrimLeftTest.php
  tests/Psl/Str/Byte/TrimRightTest.php
  tests/Psl/Str/Byte/UppercaseTest.php
  tests/Psl/Str/Byte/WordsTest.php
  tests/Psl/Str/CapitalizeWordsTest.php
  tests/Psl/Str/ChunkTest.php
  tests/Psl/Str/Grapheme/StripSuffixTest.php
  tests/Psl/Str/ReplaceEveryTest.php
  tests/Psl/Str/StartsWithCiTest.php
  tests/Psl/Str/StripSuffixTest.php
  tools/psalm/composer.json
  tools/psalm/psalm.xml
Labels: Priority: Medium, Status: Completed, Type: Maintenance

#338 feat(network): support idle connections
  examples/tcp/basic-http-server.php
  src/Psl/Channel/Internal/Receiver.php
  src/Psl/Network/Internal/AbstractStreamServer.php
  src/Psl/TCP/Server.php
  src/Psl/TCP/ServerOptions.php
Labels: Priority: High, Status: Completed, Type: Enhancement
