Repository azjezz/psl, pull requests merged in 2022-05, with the labels that each got.

#334 feat(shell): introduce error output behavior feature
  CHANGELOG.md
  config/.phpcs.xml
  docs/component/shell.md
  src/Psl/Internal/Loader.php
  src/Psl/Shell/ErrorOutputBehavior.php
  src/Psl/Shell/Exception/InvalidArgumentException.php
  src/Psl/Shell/Internal/escape_argument.php
  src/Psl/Shell/execute.php
  src/Psl/Shell/unpack.php
  tests/unit/Shell/EscapeArgumentTest.php
  tests/unit/Shell/ExecuteTest.php
  tests/unit/Shell/UnpackTest.php
Labels: Priority: Medium, Status: Accepted, Status: On Hold, Type: BC Break

#335 feat(io): add streaming function
  docs/component/io.md
  docs/component/shell.md
  src/Psl/IO/streaming.php
  src/Psl/Internal/Loader.php
  src/Psl/Shell/execute.php
Labels: Priority: Medium, Status: Revision Needed, Type: Enhancement, Experimental

#348 Use Revolt EventLoop stable version (0.2)
  composer.json
  composer.lock
Labels: Priority: High, Status: Completed, Type: Enhancement, Type: Bug

#350 Fix Filesystem\get_extension() returning empty string
  src/Psl/Filesystem/get_extension.php
  tests/unit/Filesystem/PathTest.php
Labels: Priority: Medium, Status: Completed, Type: Bug
