Repository azjezz/psl, pull requests merged in 2022-12, with the labels that each got.

#369 Support psalm v5
  composer.json
  composer.lock
  docs/component/filesystem.md
  src/Psl/Collection/MutableVector.php
  src/Psl/Collection/Vector.php
  src/Psl/Filesystem/exists.php
  src/Psl/Hash/Context.php
  src/Psl/IO/Internal/ResourceHandle.php
  src/Psl/Iter/Iterator.php
  src/Psl/Json/decode.php
  src/Psl/Json/encode.php
  src/Psl/Json/typed.php
  src/Psl/Str/Byte/split.php
  src/Psl/Str/split.php
  tests/benchmark/Type/Asset/ExplicitStringableObject.php
  tests/benchmark/Type/Asset/ImplicitStringableObject.php
  tests/static-analysis/Fun/pipe.php
Labels: Priority: Medium, Status: Accepted, Type: Enhancement

#373 feat(option): introduce `Option\from_nullable` function
  docs/README.md
  docs/component/channel.md
  docs/component/option.md
  docs/documenter.php
  src/Psl/Internal/Loader.php
  src/Psl/Option/from_nullable.php
  tests/static-analysis/Option/from_nullable.php
  tests/unit/Option/FromNullableTest.php
Labels: Priority: Medium, Status: Accepted, Status: Completed, Type: Enhancement

#378 feat: introduce `Range` component
  composer.lock
  docs/README.md
  docs/component/math.md
  docs/component/range.md
  docs/documenter.php
  src/Psl/Internal/Loader.php
  src/Psl/Iter/Iterator.php
  src/Psl/Math/constants.php
  src/Psl/Range/BetweenRange.php
  src/Psl/Range/FromRange.php
  src/Psl/Range/FullRange.php
  src/Psl/Range/LowerBoundRangeInterface.php
  src/Psl/Range/RangeInterface.php
  src/Psl/Range/ToRange.php
  src/Psl/Range/UpperBoundRangeInterface.php
  src/Psl/Range/between.php
  src/Psl/Range/from.php
  src/Psl/Range/full.php
  src/Psl/Range/to.php
  tests/unit/Range/BetweenRangeTest.php
  tests/unit/Range/FromRangeTest.php
  tests/unit/Range/FullRangeTest.php
  tests/unit/Range/ToRangeTest.php
Labels: Priority: Medium, Status: Accepted, Status: Revision Needed, Type: Enhancement

#380 feat(range): add wither methods
  docs/component/range.md
  src/Psl/Range/BetweenRange.php
  src/Psl/Range/FromRange.php
  src/Psl/Range/FullRange.php
  src/Psl/Range/LowerBoundRangeInterface.php
  src/Psl/Range/RangeInterface.php
  src/Psl/Range/ToRange.php
  src/Psl/Range/UpperBoundRangeInterface.php
  tests/unit/Range/BetweenRangeTest.php
  tests/unit/Range/FromRangeTest.php
  tests/unit/Range/FullRangeTest.php
  tests/unit/Range/ToRangeTest.php
Labels: Priority: Medium, Status: Accepted, Status: Completed, Type: Enhancement

#384 Return might be non-empty-list/non-empty-array for map functions
  src/Psl/Dict/map.php
  src/Psl/Dict/map_keys.php
  src/Psl/Dict/map_with_key.php
  src/Psl/Vec/map.php
  src/Psl/Vec/map_with_key.php
Labels: Priority: Medium, Status: Accepted, Status: Completed, Type: Enhancement

#385 feat(str): add range function
  config/.phpcs.xml
  docs/component/str-byte.md
  docs/component/str-grapheme.md
  docs/component/str.md
  src/Psl/Internal/Loader.php
  src/Psl/Str/Byte/range.php
  src/Psl/Str/Grapheme/range.php
  src/Psl/Str/Grapheme/slice.php
  src/Psl/Str/range.php
  tests/unit/Str/Byte/RangeTest.php
  tests/unit/Str/Grapheme/RangeTest.php
  tests/unit/Str/RangeTest.php
Labels: Priority: Medium, Status: Accepted, Status: Review Needed, Type: Enhancement
