Repository azjezz/psl, pull requests merged in 2023-11, with the labels that each got.

#427 Fix mutations + math float tests
  config/infection.json.dist
  config/phpunit.xml.dist
  src/Psl/Collection/MutableMap.php
  tests/unit/Collection/AbstractMapTest.php
  tests/unit/Collection/MapTest.php
  tests/unit/Collection/MutableMapTest.php
  tests/unit/DataStructure/PriorityQueueTest.php
  tests/unit/File/ReadHandleTest.php
  tests/unit/Math/AcosTest.php
  tests/unit/Math/AsinTest.php
  tests/unit/Math/Atan2Test.php
  tests/unit/Math/AtanTest.php
  tests/unit/Math/CosTest.php
  tests/unit/Math/FloatAsserts.php
  tests/unit/Math/SinTest.php
  tests/unit/Math/TanTest.php
Labels: Priority: High, Status: Accepted, Type: Enhancement

#428 Introduce a comparison component
  docs/README.md
  docs/component/comparison.md
  docs/component/option.md
  docs/documenter.php
  src/Psl/Comparison/Comparable.php
  src/Psl/Comparison/Equable.php
  src/Psl/Comparison/Exception/IncomparableException.php
  src/Psl/Comparison/Order.php
  src/Psl/Comparison/compare.php
  src/Psl/Comparison/equal.php
  src/Psl/Comparison/greater.php
  src/Psl/Comparison/greater_or_equal.php
  src/Psl/Comparison/less.php
  src/Psl/Comparison/less_or_equal.php
  src/Psl/Comparison/not_equal.php
  src/Psl/Comparison/sort.php
  src/Psl/Internal/Loader.php
  src/Psl/Option/Option.php
  tests/static-analysis/Comparison/comparable.php
  tests/unit/Comparison/AbstractComparisonTest.php
  tests/unit/Comparison/CompareTest.php
  tests/unit/Comparison/EqualTest.php
  tests/unit/Comparison/GreaterOrEqualTest.php
  tests/unit/Comparison/GreaterTest.php
  tests/unit/Comparison/LessOrEqualTest.php
  tests/unit/Comparison/LessTest.php
  tests/unit/Comparison/NotEqualTest.php
  tests/unit/Comparison/SortTest.php
  tests/unit/Option/NoneTest.php
  tests/unit/Option/SomeTest.php
Labels: Priority: Low, Status: Accepted, Type: Enhancement

#430 Indicate support for PHP 8.3
  .github/workflows/unit-tests.yml
  composer.json
  composer.lock
  src/Psl/Html/strip_tags.php
Labels: Priority: High, Status: Accepted, Type: Maintenance
