Repository azjezz/psl, pull requests merged in 2023-01, with the labels that each got.

#386 doc(async): add documentation
  docs/README.md
  docs/component/async.md
  docs/documenter.php
  docs/templates/README.template.md
  src/Psl/Async/Awaitable.php
  src/Psl/Async/KeyedSemaphore.php
  src/Psl/Async/KeyedSequence.php
  src/Psl/Async/README.md
  src/Psl/Async/Semaphore.php
  src/Psl/Async/Sequence.php
Labels: Priority: Medium, Status: Accepted, Status: Review Needed, Type: Enhancement, Type: Documentation

#391 chore: remove float ranges
  docs/README.md
  docs/component/range.md
  docs/documenter.php
  docs/templates/README.template.md
  src/Psl/Async/README.md
  src/Psl/Math/constants.php
  src/Psl/Range/BetweenRange.php
  src/Psl/Range/Exception/ExceptionInterface.php
  src/Psl/Range/Exception/InvalidRangeException.php
  src/Psl/Range/Exception/OverflowException.php
  src/Psl/Range/FromRange.php
  src/Psl/Range/FullRange.php
  src/Psl/Range/LowerBoundRangeInterface.php
  src/Psl/Range/README.md
  src/Psl/Range/RangeInterface.php
  src/Psl/Range/ToRange.php
  src/Psl/Range/UpperBoundRangeInterface.php
  src/Psl/Range/between.php
  src/Psl/Range/from.php
  src/Psl/Range/full.php
  src/Psl/Range/to.php
  src/Psl/Str/Byte/range.php
  src/Psl/Str/Grapheme/range.php
  src/Psl/Str/range.php
  tests/unit/Range/BetweenRangeTest.php
  tests/unit/Range/FromRangeTest.php
  tests/unit/Range/FullRangeTest.php
  tests/unit/Range/ToRangeTest.php
  tests/unit/Str/Byte/RangeTest.php
  tests/unit/Str/Grapheme/RangeTest.php
  tests/unit/Str/RangeTest.php
Labels: Priority: High, Status: Completed, Type: Enhancement

#392 feat(type): add nonnull type
  docs/component/type.md
  src/Psl/Internal/Loader.php
  src/Psl/Type/Internal/NonNullType.php
  src/Psl/Type/nonnull.php
  tests/unit/Type/NonNullTypeTest.php
Labels: Priority: High, Status: Completed, Type: Enhancement

#393 feat(type): add uint type
  docs/component/type.md
  src/Psl/Internal/Loader.php
  src/Psl/Type/Internal/UIntType.php
  src/Psl/Type/positive_int.php
  src/Psl/Type/uint.php
  tests/unit/Type/UIntTypeTest.php
Labels: Priority: High, Status: Accepted, Type: Enhancement

#394 feat(type): add signed integer types
  CHANGELOG.md
  docs/component/type.md
  src/Psl/Internal/Loader.php
  src/Psl/Math/constants.php
  src/Psl/Type/Internal/I16Type.php
  src/Psl/Type/Internal/I32Type.php
  src/Psl/Type/Internal/I64Type.php
  src/Psl/Type/Internal/I8Type.php
  src/Psl/Type/Internal/VecType.php
  src/Psl/Type/i16.php
  src/Psl/Type/i32.php
  src/Psl/Type/i64.php
  src/Psl/Type/i8.php
  tests/unit/Type/I16TypeTest.php
  tests/unit/Type/I32TypeTest.php
  tests/unit/Type/I64TypeTest.php
  tests/unit/Type/I8TypeTest.php
Labels: Priority: High, Status: Completed, Type: Enhancement

#395 feat(type): add unsigned integer types
  docs/component/type.md
  src/Psl/Internal/Loader.php
  src/Psl/Type/Internal/U16Type.php
  src/Psl/Type/Internal/U32Type.php
  src/Psl/Type/Internal/U8Type.php
  src/Psl/Type/u16.php
  src/Psl/Type/u32.php
  src/Psl/Type/u8.php
  tests/unit/Type/U16TypeTest.php
  tests/unit/Type/U32TypeTest.php
  tests/unit/Type/U8TypeTest.php
Labels: Priority: High, Status: Accepted, Status: Completed, Type: Enhancement

#398 Improve options type declarations and add andThen method
  src/Psl/Option/Option.php
  tests/static-analysis/Option/unwrap.php
  tests/unit/Option/NoneTest.php
  tests/unit/Option/SomeTest.php
Labels: Priority: Medium, Status: Accepted, Status: Completed, Type: Enhancement
