Repository azjezz/psl, pull requests merged in 2023-12, with the labels that each got.

#435 feat(type): add class_string types (#432)
  docs/component/type.md
  src/Psl/Internal/Loader.php
  src/Psl/Type/Internal/ClassStringType.php
  src/Psl/Type/class_string.php
  tests/static-analysis/Type/class_string.php
  tests/unit/Type/ClassStringTypeTest.php
Labels: Priority: Medium, Status: Completed, Type: Enhancement

#434 feat(option): add `Option::zip()`, `Option::zipWith()` and `Option::unzip()` methods
  docs/component/option.md
  src/Psl/Option/Option.php
  tests/fixture/Point.php
  tests/static-analysis/Option/zip.php
  tests/unit/Option/NoneTest.php
  tests/unit/Option/SomeTest.php
Labels: Priority: Medium, Status: Accepted, Type: Enhancement

#433 feat(option): add `Option::proceed()` method
  src/Psl/Option/Option.php
  tests/static-analysis/Option/proceed.php
  tests/unit/Option/NoneTest.php
  tests/unit/Option/SomeTest.php
Labels: Priority: Medium, Status: Accepted, Type: Enhancement

#426 feat(option): new `Option::apply()` method
  src/Psl/Option/Option.php
  tests/unit/Option/NoneTest.php
  tests/unit/Option/SomeTest.php
Labels: Priority: Low, Status: Accepted, Type: Enhancement
