Repository azjezz/psl, pull requests merged in 2024-04, with the labels that each got.

#459 fix(type): Positive int has a broken exception path
  src/Psl/Type/Internal/PositiveIntType.php
Labels: Priority: Medium, Status: Review Needed, Type: Enhancement

#456 Fix PHP84 implicit nullable types
  config/.php_cs.dist.php
  src/Psl/Vec/range.php
  tests/unit/Dict/SliceTest.php
  tests/unit/Regex/EveryMatchTest.php
  tests/unit/Regex/FirstMatchTest.php
  tests/unit/Vec/SliceTest.php
Labels: Priority: Low, Status: Review Needed, Type: Maintenance

#460 Fix PHP84 nullable types
  config/.php_cs.dist.php
  src/Psl/Vec/range.php
  tests/unit/Dict/SliceTest.php
  tests/unit/Regex/EveryMatchTest.php
  tests/unit/Regex/FirstMatchTest.php
  tests/unit/Vec/SliceTest.php
Labels: Priority: Medium, Status: Completed, Type: Maintenance

#463 feat(type): Mark type classes as readonly
  src/Psl/Type/Internal/ArrayKeyType.php
  src/Psl/Type/Internal/BackedEnumType.php
  src/Psl/Type/Internal/BoolType.php
  src/Psl/Type/Internal/ClassStringType.php
  src/Psl/Type/Internal/ConvertedType.php
  src/Psl/Type/Internal/DictType.php
  src/Psl/Type/Internal/F32Type.php
  src/Psl/Type/Internal/F64Type.php
  src/Psl/Type/Internal/FloatType.php
  src/Psl/Type/Internal/I16Type.php
  src/Psl/Type/Internal/I32Type.php
  src/Psl/Type/Internal/I64Type.php
  src/Psl/Type/Internal/I8Type.php
  src/Psl/Type/Internal/InstanceOfType.php
  src/Psl/Type/Internal/IntType.php
  src/Psl/Type/Internal/IntersectionType.php
  src/Psl/Type/Internal/IterableType.php
  src/Psl/Type/Internal/LiteralScalarType.php
  src/Psl/Type/Internal/MapType.php
  src/Psl/Type/Internal/MixedDictType.php
  src/Psl/Type/Internal/MixedType.php
  src/Psl/Type/Internal/MixedVecType.php
  src/Psl/Type/Internal/MutableMapType.php
  src/Psl/Type/Internal/MutableVectorType.php
  src/Psl/Type/Internal/NonEmptyDictType.php
  src/Psl/Type/Internal/NonEmptyStringType.php
  src/Psl/Type/Internal/NonEmptyVecType.php
  src/Psl/Type/Internal/NonNullType.php
  src/Psl/Type/Internal/NullType.php
  src/Psl/Type/Internal/NullableType.php
  src/Psl/Type/Internal/NumType.php
  src/Psl/Type/Internal/NumericStringType.php
  src/Psl/Type/Internal/ObjectType.php
  src/Psl/Type/Internal/OptionalType.php
  src/Psl/Type/Internal/PathExpression.php
  src/Psl/Type/Internal/PositiveIntType.php
  src/Psl/Type/Internal/ResourceType.php
  src/Psl/Type/Internal/ScalarType.php
  src/Psl/Type/Internal/ShapeType.php
  src/Psl/Type/Internal/StringType.php
  src/Psl/Type/Internal/U16Type.php
  src/Psl/Type/Internal/U32Type.php
  src/Psl/Type/Internal/U8Type.php
  src/Psl/Type/Internal/UIntType.php
  src/Psl/Type/Internal/UnionType.php
  src/Psl/Type/Internal/UnitEnumType.php
  src/Psl/Type/Internal/VecType.php
  src/Psl/Type/Internal/VectorType.php
  src/Psl/Type/Type.php
  tests/unit/Class/ClassTest.php
Labels: Priority: Medium, Status: Completed, Type: Enhancement

#464 feat: narrow return type for `min()`, `max()`, `median()` and `mean()`
  docs/component/math.md
  src/Psl/Math/max.php
  src/Psl/Math/mean.php
  src/Psl/Math/median.php
  src/Psl/Math/min.php
Labels: Priority: Medium, Status: Completed, Type: Enhancement

#465 feat(type): Notnull type optimizations
  docs/component/type.md
  src/Psl/Type/Internal/NonNullType.php
  src/Psl/Type/nonnull.php
  tests/static-analysis/Type/nonnull.php
Labels: Priority: Low, Status: Review Needed, Type: Enhancement

#462 docs(type): Provides an initial documentation document for the Type component
  docs/README.md
  docs/component/type.md
  docs/documenter.php
  docs/templates/README.template.md
  src/Psl/Type/README.md
Labels: Priority: Medium, Status: In Progress, Type: Documentation

#466 feat: narrow ResultInterface to concrete implementation after calling `isSucceeded()` and `isFailed()`
  src/Psl/Result/ResultInterface.php
  tests/static-analysis/Result/result_interface.php
Labels: Priority: Medium, Status: Completed, Type: Enhancement

#471 Change `Iter\apply` `(Closure(T): void)` `$function` to `(Closure(T): mixed)`
  src/Psl/Iter/apply.php
Labels: Priority: Medium, Status: Review Needed, Type: Enhancement
