Repository azjezz/psl, pull requests merged in 2025-03, with the labels that each got.

#511 chore: update mago to version 0.13
  Makefile
  composer.json
  composer.lock
  examples/tcp/basic-http-server.php
  src/Psl/DateTime/DateTime.php
  src/Psl/Filesystem/read_directory.php
  src/Psl/Iter/Iterator.php
  tests/benchmark/Type/ShapeTypeBench.php
  tests/unit/Collection/AbstractMapTest.php
  tests/unit/Collection/AbstractSetTest.php
  tests/unit/Collection/AbstractVectorTest.php
  tests/unit/Collection/MutableMapTest.php
  tests/unit/Collection/MutableSetTest.php
  tests/unit/Dict/PullTest.php
  tests/unit/Dict/PullWithKeyTest.php
  tests/unit/Filesystem/DirectoryTest.php
  tests/unit/Iter/IteratorTest.php
  tests/unit/Json/DecodeTest.php
  tests/unit/Json/EncodeTest.php
  tests/unit/Runtime/VersionTest.php
  tests/unit/TCP/ServerTest.php
  tests/unit/Type/ShapeAllowUnknownFieldsTypeTest.php
  tests/unit/Type/ShapeTypeTest.php
Labels: Priority: High, Status: Review Needed, Type: Maintenance, Type: Enhancement

#513 feat(type): add container type
  src/Psl/Internal/Loader.php
  src/Psl/Type/Internal/ContainerType.php
  src/Psl/Type/container.php
  tests/unit/Type/ContainerTypeTest.php
Labels: Priority: Critical, Status: Completed, Type: Enhancement

#512 chore(collection): use a more natural JSON serialization for Sets and Maps
  docs/component/collection.md
  src/Psl/Collection/CollectionInterface.php
  src/Psl/Collection/Map.php
  src/Psl/Collection/MutableMap.php
  src/Psl/Collection/MutableSet.php
  src/Psl/Collection/Set.php
  tests/unit/Collection/AbstractMapTest.php
  tests/unit/Collection/MutableSetTest.php
  tests/unit/Collection/SetTest.php
Labels: Priority: Critical, Status: Completed, Type: Enhancement, Type: BC Break

#517 bump MSPV to 8.3.0
  .github/workflows/benchmarks.yml
  .github/workflows/code-coverage.yml
  .github/workflows/coding-standards.yml
  .github/workflows/mutation-tests.yml
  .github/workflows/preload-check.yml
  .github/workflows/security-analysis.yml
  .github/workflows/static-analysis.yml
  .github/workflows/unit-tests.yml
  composer.json
  composer.lock
  config/mago.toml
  config/psalm.xml
  examples/shell/concurrent.php
  src/Psl/IO/Internal/ResourceHandle.php
  src/Psl/Internal/Loader.php
  src/Psl/Network/Address.php
  src/Psl/Network/Internal/AbstractStreamServer.php
  src/Psl/TCP/ServerOptions.php
  tests/unit/Type/ConvertedTypeTest.php
Labels: Priority: Critical, Status: Completed, Type: Maintenance, Type: BC Break

#510 feat(type): add `int_range` type
  src/Psl/Internal/Loader.php
  src/Psl/Type/Internal/IntRangeType.php
  src/Psl/Type/README.md
  src/Psl/Type/int_range.php
  tests/unit/Type/IntRangeTypeTest.php
Labels: Priority: Medium, Status: Revision Needed, Type: Enhancement

#519 chore: remove `Psl\sequence` function
  docs/component/psl.md
  src/Psl/Internal/Loader.php
  src/Psl/sequence.php
  tests/unit/SequenceTest.php
Labels: Priority: High, Status: Completed, Type: Maintenance, Type: BC Break

#521 chore: update mago to version 0.20.0
  composer.json
  composer.lock
  config/mago.toml
  src/Psl/Async/Semaphore.php
  src/Psl/Async/Sequence.php
  src/Psl/DateTime/TemporalConvenienceMethodsTrait.php
  src/Psl/Encoding/Base64/Internal/Base64.php
  src/Psl/Env/args.php
  src/Psl/Env/current_exec.php
  src/Psl/File/Internal/ResourceHandle.php
  src/Psl/Filesystem/create_temporary_file.php
  src/Psl/Filesystem/file_size.php
  src/Psl/Filesystem/get_access_time.php
  src/Psl/Filesystem/get_change_time.php
  src/Psl/Filesystem/get_inode.php
  src/Psl/Filesystem/get_modification_time.php
  src/Psl/Filesystem/get_permissions.php
  src/Psl/Filesystem/read_symbolic_link.php
  src/Psl/Hash/Context.php
  src/Psl/IO/Reader.php
  src/Psl/IO/pipe.php
  src/Psl/Internal/Loader.php
  src/Psl/Internal/constants.php
  src/Psl/Iter/Iterator.php
  src/Psl/Math/base_convert.php
  src/Psl/RandomSequence/Internal/MersenneTwisterTrait.php
  src/Psl/Regex/Internal/call_preg.php
  src/Psl/Shell/execute.php
  src/Psl/Shell/unpack.php
  src/Psl/Str/constants.php
  src/Psl/Str/wrap.php
  src/Psl/Type/Internal/ContainerType.php
  src/Psl/Type/Internal/IntersectionType.php
  src/Psl/Type/Internal/IterableType.php
  src/Psl/Type/Internal/MutableMapType.php
  src/Psl/Type/Internal/UnionType.php
  src/Psl/Unix/Server.php
  src/Psl/Unix/connect.php
  tests/benchmark/Type/Asset/ImplicitStringableObject.php
  tests/static-analysis/Str/before.php
  tests/static-analysis/Str/chunk.php
  tests/static-analysis/Str/repeat.php
  tests/static-analysis/Str/splice.php
  tests/static-analysis/Str/split.php
  tests/unit/Collection/AbstractSetTest.php
  tests/unit/Comparison/AbstractComparisonTest.php
  tests/unit/DateTime/DurationTest.php
  tests/unit/DateTime/TimestampTest.php
  tests/unit/Fun/LazyTest.php
  tests/unit/Iter/IteratorTest.php
  tests/unit/Iter/SearchOptTest.php
  tests/unit/Iter/SearchWithKeysOptTest.php
  tests/unit/Iter/SearchWithKeysTest.php
  tests/unit/Locale/LocaleTest.php
  tests/unit/TCP/ServerOptionsTest.php
  tests/unit/TCP/ServerTest.php
  tests/unit/Type/TypeTest.php
Labels: Priority: High, Status: Completed, Type: Maintenance

#522 feat(type): add always_assert type
  src/Psl/Internal/Loader.php
  src/Psl/Type/Internal/AlwaysAssertType.php
  src/Psl/Type/README.md
  src/Psl/Type/always_assert.php
  tests/unit/Type/AlwaysAssertTypeTest.php
Labels: Status: Completed, Type: Enhancement
